var g;g||=typeof Module != 'undefined' ? Module : {};var aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&globalThis.process?.type!="renderer";g.expectedDataFileDownloads||(g.expectedDataFileDownloads=0);g.expectedDataFileDownloads++;
(()=>{var a=typeof ENVIRONMENT_IS_WASM_WORKER!="undefined"&&ENVIRONMENT_IS_WASM_WORKER;if(!(typeof ENVIRONMENT_IS_PTHREAD!="undefined"&&ENVIRONMENT_IS_PTHREAD||a)){var b=globalThis.process&&globalThis.process.versions&&globalThis.process.versions.node&&globalThis.process.type!="renderer";(async function(c){async function d(n,q){if(b){var w=require("fs").readFileSync(n);return(new Uint8Array(w)).buffer}g.dataFileDownloads||(g.dataFileDownloads={});try{var z=await fetch(n)}catch(N){throw Error(`Network Error: ${n}`,
{e:N});}if(!z.ok)throw Error(`${z.status}: ${z.url}`);w=[];q=Number(z.headers.get("Content-Length")||q);var G=0;g.setStatus&&g.setStatus("Downloading data...");for(z=z.body.getReader();;){var F;({done:F,value:L}=await z.read());if(F)break;w.push(L);G+=L.length;g.dataFileDownloads[n]={loaded:G,total:q};var L=F=0;for(var H of Object.values(g.dataFileDownloads))F+=H.loaded,L+=H.total;g.setStatus&&g.setStatus(`Downloading data... (${F}/${L})`)}n=new Uint8Array(w.map(N=>N.length).reduce((N,T)=>N+T,0));
H=0;for(let N of w)n.set(N,H),H+=N.length;return n.buffer}async function e(n){n.FS_createPath("/","run-tree",!0,!0);n.FS_createPath("/run-tree","data",!0,!0);n.FS_createPath("/run-tree/data","beatup",!0,!0);n.FS_createPath("/run-tree/data/beatup","audio",!0,!0);n.FS_createPath("/run-tree/data/beatup","config",!0,!0);n.FS_createPath("/run-tree/data/beatup","song",!0,!0);n.FS_createPath("/run-tree/data/beatup","texture",!0,!0);n.FS_createPath("/run-tree/data","fonts",!0,!0);n.addRunDependency("datafile_dist/beatup_wasm/beatup_run.data");
n.preloadResults||(n.preloadResults={});n.preloadResults["dist/beatup_wasm/beatup_run.data"]={Mj:!1};m||=await k;await async function(q){if(!q)throw Error("Loading data file failed.");if(q.constructor.name!==ArrayBuffer.name)throw Error("bad input to processPackageData "+q.constructor.name);q=new Uint8Array(q);for(var w of c.files)n.FS_createDataFile(w.filename,null,q.subarray(w.start,w.end),!0,!0,!0);n.removeRunDependency("datafile_dist/beatup_wasm/beatup_run.data")}(m)}typeof window==="object"?
window.encodeURIComponent(window.location.pathname.substring(0,window.location.pathname.lastIndexOf("/"))+"/"):typeof process==="undefined"&&typeof location!=="undefined"&&encodeURIComponent(location.pathname.substring(0,location.pathname.lastIndexOf("/"))+"/");var f=g.locateFile?g.locateFile("beatup_run.data",""):"beatup_run.data",h=c.remote_package_size,k,m=g.getPreloadedPackage&&g.getPreloadedPackage(f,h);m||(k=d(f,h));g.FS_createPath?e(g):(g.preRun||(g.preRun=[]),g.preRun.push(e))})({files:[{filename:"/run-tree/data/beatup/audio/miss.wav",
start:0,end:28602},{filename:"/run-tree/data/beatup/audio/normal.wav",start:28602,end:37934},{filename:"/run-tree/data/beatup/audio/perfect.wav",start:37934,end:50800},{filename:"/run-tree/data/beatup/audio/space.wav",start:50800,end:104672},{filename:"/run-tree/data/beatup/config/engine_beatup.scf",start:104672,end:106947},{filename:"/run-tree/data/beatup/config/keybind_beatup.scf",start:106947,end:107310},{filename:"/run-tree/data/beatup/song/song1.ogg",start:107310,end:4390137},{filename:"/run-tree/data/beatup/song/song2.ogg",
start:4390137,end:7426894},{filename:"/run-tree/data/beatup/song/song_1_beatup.scf",start:7426894,end:7434573},{filename:"/run-tree/data/beatup/song/song_2_beatup.scf",start:7434573,end:7437947},{filename:"/run-tree/data/beatup/texture/sprite_sheet.png",start:7437947,end:8083054},{filename:"/run-tree/data/beatup/texture/sprite_sheet.scf",start:8083054,end:8085054},{filename:"/run-tree/data/fonts/Lora-Regular.ttf",start:8085054,end:8218942},{filename:"/run-tree/data/fonts/roboto_slab.ttf",start:8218942,
end:8470822}],remote_package_size:8470822})}})();var da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha=globalThis.document?.currentScript?.src;typeof __filename!="undefined"?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("node:fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};process.argv.length>1&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);typeof module!="undefined"&&(module.exports=g);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{e.status==200||e.status==0&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ma=console.log.bind(console),l=console.error.bind(console),na=!1,oa,la=a=>a.startsWith("file://");
function pa(){if(!p?.buffer?.resizable){var a=qa.buffer;p=new Int8Array(a);ra=new Int16Array(a);r=new Uint8Array(a);sa=new Uint16Array(a);t=new Int32Array(a);u=new Uint32Array(a);v=new Float32Array(a);x=new Float64Array(a);ta=new BigInt64Array(a)}}function ua(){var a=g.preRun;a&&(typeof a=="function"&&(a=[a]),va.push(...a));for(a=va;a.length>0;)a.shift()(g)}function wa(){var a=g.postRun;a&&(typeof a=="function"&&(a=[a]),xa.push(...a));for(a=xa;a.length>0;)a.shift()(g)}
function y(a){g.onAbort?.(a);a=`Aborted(${a})`;l(a);na=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ya;async function za(a){try{var b=await ja(a);return new Uint8Array(b)}catch{}if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function Aa(a,b){try{var c=await za(a);return await WebAssembly.instantiate(c,b)}catch(d){l(`failed to asynchronously prepare wasm: ${d}`),y(d)}}
async function Ba(a){var b=ya;if(!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){l(`wasm streaming compile failed: ${d}`),l("falling back to ArrayBuffer instantiation")}return Aa(b,a)}class Ca{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var p,xa=[],va=[],Da=!0,t,Fa=()=>{var a=t[+Ea>>2];Ea+=4;return a},Ga=(a,b)=>{for(var c=0,d=a.length-1;d>=0;d--){var e=a[d];e==="."?a.splice(d,1):e===".."?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Ha=a=>{var b=a.charAt(0)==="/",c=a.slice(-1)==="/";(a=Ga(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Ia=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&
!b)return".";b&&=b.slice(0,-1);return a+b},Ja=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],Ka=()=>{if(ca){var a=require("node:crypto");return b=>(a.randomFillSync(b),0)}return b=>(crypto.getRandomValues(b),0)},La=a=>(La=Ka())(a),Ma=(...a)=>{for(var b="",c=!1,d=a.length-1;d>=-1&&!c;d--){c=d>=0?a[d]:"/";if(typeof c!="string")throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c=c.charAt(0)==="/"}b=Ga(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Na=
globalThis.TextDecoder&&new TextDecoder,A=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(d-b>16&&a.buffer&&Na)return Na.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var f=a[b++]&63;if((e&224)==192)c+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=(e&240)==224?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;e<65536?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},Oa=[],Pa=a=>{for(var b=0,
c=0;c<a.length;++c){var d=a.charCodeAt(c);d<=127?b++:d<=2047?b+=2:d>=55296&&d<=57343?(b+=4,++c):b+=3}return b},B=(a,b,c,d)=>{if(!(d>0))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.codePointAt(f);if(h<=127){if(c>=d)break;b[c++]=h}else if(h<=2047){if(c+1>=d)break;b[c++]=192|h>>6;b[c++]=128|h&63}else if(h<=65535){if(c+2>=d)break;b[c++]=224|h>>12;b[c++]=128|h>>6&63;b[c++]=128|h&63}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63;b[c++]=128|h>>6&63;b[c++]=128|h&63;f++}}b[c]=0;
return c-e},Qa=a=>{var b=Array(Pa(a)+1);a=B(a,b,0,b.length);b.length=a;return b},Ra=[];function Sa(a,b){Ra[a]={input:[],output:[],hh:b};Ta(a,Ua)}
var Ua={open(a){var b=Ra[a.node.rdev];if(!b)throw new C(43);a.tty=b;a.seekable=!1},close(a){a.tty.hh.fsync(a.tty)},fsync(a){a.tty.hh.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.hh.Ji)throw new C(60);for(var e=0,f=0;f<d;f++){try{var h=a.tty.hh.Ji(a.tty)}catch(k){throw new C(29);}if(h===void 0&&!e)throw new C(6);if(h===null||h===void 0)break;e++;b[c+f]=h;if(h===10)break}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.hh.ti)throw new C(60);try{for(var e=0;e<d;e++)a.tty.hh.ti(a.tty,
b[c+e])}catch(f){throw new C(29);}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},Va={Ji(){a:{if(!Oa.length){var a=null;if(ca){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}c>0&&(a=b.slice(0,c).toString("utf-8"))}else globalThis.window?.prompt&&(a=window.prompt("Input: "),a!==null&&(a+="\n"));if(!a){a=null;break a}Oa=Qa(a)}a=Oa.shift()}return a},ti(a,b){b===null||b===10?(ma(A(a.output)),a.output=[]):b!=0&&
a.output.push(b)},fsync(a){a.output?.length>0&&(ma(A(a.output)),a.output=[])},hj(){return{Bj:25856,Dj:5,Aj:191,Cj:35387,zj:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},ij(){return 0},jj(){return[24,80]}},Wa={ti(a,b){b===null||b===10?(l(A(a.output)),a.output=[]):b!=0&&a.output.push(b)},fsync(a){a.output?.length>0&&(l(A(a.output)),a.output=[])}},D={dh:null,gh(){return D.createNode(null,"/",16895,0)},createNode(a,b,c,d){if((c&61440)===24576||(c&61440)===4096)throw new C(63);
D.dh||(D.dh={dir:{node:{Xg:D.Fg.Xg,ih:D.Fg.ih,lookup:D.Fg.lookup,Th:D.Fg.Th,rename:D.Fg.rename,unlink:D.Fg.unlink,rmdir:D.Fg.rmdir,readdir:D.Fg.readdir,symlink:D.Fg.symlink},stream:{bh:D.Gg.bh}},file:{node:{Xg:D.Fg.Xg,ih:D.Fg.ih},stream:{bh:D.Gg.bh,read:D.Gg.read,write:D.Gg.write,oi:D.Gg.oi,Ni:D.Gg.Ni}},link:{node:{Xg:D.Fg.Xg,ih:D.Fg.ih,readlink:D.Fg.readlink},stream:{}},Gi:{node:{Xg:D.Fg.Xg,ih:D.Fg.ih},stream:Xa}});c=Ya(a,b,c,d);E(c.mode)?(c.Fg=D.dh.dir.node,c.Gg=D.dh.dir.stream,c.Ig={}):(c.mode&
61440)===32768?(c.Fg=D.dh.file.node,c.Gg=D.dh.file.stream,c.Qg=0,c.Ig=D.Zi??(D.Zi=new Uint8Array(0))):(c.mode&61440)===40960?(c.Fg=D.dh.link.node,c.Gg=D.dh.link.stream):(c.mode&61440)===8192&&(c.Fg=D.dh.Gi.node,c.Gg=D.dh.Gi.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.Ig[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},Fg:{Xg(a){var b={};b.dev=(a.mode&61440)===8192?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;E(a.mode)?b.size=4096:(a.mode&61440)===32768?b.size=a.Qg:(a.mode&
61440)===40960?b.size=a.link.length:b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},ih(a,b){for(var c of["mode","atime","mtime","ctime"])b[c]!=null&&(a[c]=b[c]);b.size!==void 0&&(b=b.size,a.Qg!=b&&(c=a.Ig,a.Ig=new Uint8Array(b),a.Ig.set(c.subarray(0,Math.min(b,a.Qg))),a.Qg=b))},lookup(){D.bi||(D.bi=new C(44),D.bi.stack="<generic error, no stack>");throw D.bi;},Th(a,b,c,d){return D.createNode(a,b,c,
d)},rename(a,b,c){try{var d=Za(b,c)}catch(f){}if(d){if(E(a.mode))for(var e in d.Ig)throw new C(55);$a(d)}delete a.parent.Ig[a.name];b.Ig[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.Ig[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=Za(a,b),d;for(d in c.Ig)throw new C(55);delete a.Ig[b];a.ctime=a.mtime=Date.now()},readdir(a){return[".","..",...Object.keys(a.Ig)]},symlink(a,b,c){a=D.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if((a.mode&61440)!==
40960)throw new C(28);return a.link}},Gg:{read(a,b,c,d,e){if(e>=a.node.Qg)return 0;d=Math.min(a.node.Qg-e,d);b.set(a.node.Ig.subarray(e,e+d),c);return d},write(a,b,c,d,e,f){b.buffer===p.buffer&&(f=!1);if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(f)a.Ig=b.subarray(c,c+d),a.Qg=d;else if(a.Qg||e){f=e+d;var h=a.Ig.length;h>=f||(f=Math.max(f,h*(h<1048576?2:1.125)>>>0),h&&(f=Math.max(f,256)),h=a.Ig.subarray(0,a.Qg),a.Ig=new Uint8Array(f),a.Ig.set(h));a.Ig.set(b.subarray(c,c+d),e);a.Qg=Math.max(a.Qg,
e+d)}else a.Ig=b.slice(c,c+d),a.Qg=d;return d},bh(a,b,c){c===1?b+=a.position:c===2&&(a.node.mode&61440)===32768&&(b+=a.node.Qg);if(b<0)throw new C(28);return b},oi(a,b,c,d,e){if((a.node.mode&61440)!==32768)throw new C(43);a=a.node.Ig;if(e&2||a.buffer!==p.buffer){d=!0;y();e=void 0;if(!e)throw new C(48);if(a){if(c>0||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);p.set(a,e)}}else d=!1,e=a.byteOffset;return{Vh:e,wj:d}},Ni(a,b,c,d){D.Gg.write(a,b,0,d,c,!1);return 0}}},
ab=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},bb=async a=>{a=await ja(a);return new Uint8Array(a)},cb=null,db=async()=>cb,eb=0,fb=null,gb=()=>{eb--;g.monitorRunDependencies?.(eb);eb||fb()},hb=()=>{eb||(cb=new Promise(a=>fb=a));eb++;g.monitorRunDependencies?.(eb)},ib=[],lb=async(a,b)=>{typeof jb!="undefined"&&kb();for(var c of ib)if(c.canHandle(b))return c.handle(a,b);return a},mb=null,nb={},ob=[],pb=1,qb=null,rb=!1,sb=!0,C=class{name="ErrnoError";constructor(a){this.Ng=a}},tb=class{shared=
{};node=null;get flags(){return this.shared.flags}set flags(a){this.shared.flags=a}get position(){return this.shared.position}set position(a){this.shared.position=a}},ub=class{Fg={};Gg={};uh=null;listeners=null;Mg=0;constructor(a,b,c,d){a||=this;this.parent=a;this.gh=a.gh;this.id=pb++;this.name=b;this.mode=c;this.rdev=d;this.atime=this.mtime=this.ctime=Date.now()}get read(){return(this.mode&365)===365}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return(this.mode&146)===146}set write(a){a?
this.mode|=146:this.mode&=-147}get lj(){return E(this.mode)}get kj(){return(this.mode&61440)===8192}oj(){if(this.listeners){var a;for(b of this.listeners)b.exclusive?(a||=[]).push(b):b.cb(32);if(a){var b=(this.Mg||0)%a.length;this.Mg=b+1;a[b].cb(32)}}}};
function vb(a,b={}){if(!a)throw new C(44);b.gi??(b.gi=!0);a.charAt(0)==="/"||(a="//"+a);var c=0;a:for(;c<40;c++){a=a.split("/").filter(k=>!!k);for(var d=mb,e="/",f=0;f<a.length;f++){var h=f===a.length-1;if(h&&b.parent)break;if(a[f]!==".")if(a[f]==="..")if(e=Ia(e),d===d.parent){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=Ha(e+"/"+a[f]);try{d=Za(d,a[f])}catch(k){if(k?.Ng===44&&h&&b.nj)return{path:e};throw k;}!d.uh||h&&!b.gi||(d=d.uh.root);if((d.mode&61440)===40960&&(!h||b.Oh)){if(!d.Fg.readlink)throw new C(52);
d=d.Fg.readlink(d);d.charAt(0)==="/"||(d=Ia(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new C(32);}function wb(a){for(var b;;){if(a===a.parent)return a=a.gh.Mi,b?a[a.length-1]!=="/"?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function xb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%qb.length}
function $a(a){var b=xb(a.parent.id,a.name);if(qb[b]===a)qb[b]=a.wh;else for(b=qb[b];b;){if(b.wh===a){b.wh=a.wh;break}b=b.wh}}function Za(a,b){var c=E(a.mode)?(c=yb(a,"x"))?c:a.Fg.lookup?0:2:54;if(c)throw new C(c);for(c=qb[xb(a.id,b)];c;c=c.wh){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Fg.lookup(a,b)}function Ya(a,b,c,d){a=new ub(a,b,c,d);b=xb(a.parent.id,a.name);a.wh=qb[b];return qb[b]=a}function E(a){return(a&61440)===16384}
function yb(a,b){return sb?0:b.includes("r")&&!(a.mode&292)||b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73)?2:0}function zb(a,b){if(!E(a.mode))return 54;try{return Za(a,b),20}catch(c){}return yb(a,"wx")}function Ab(a,b,c){try{var d=Za(a,b)}catch(e){return e.Ng}if(a=yb(a,"wx"))return a;if(c){if(!E(d.mode))return 54;if(d===d.parent||wb(d)==="/")return 10}else if(E(d.mode))return 31;return 0}function Bb(a){if(!a)throw new C(63);return a}
function Cb(a){a=ob[a];if(!a)throw new C(8);return a}function Db(a,b=-1){a=Object.assign(new tb,a);if(b==-1)a:{for(b=0;b<=4096;b++)if(!ob[b])break a;throw new C(33);}a.fd=b;return ob[b]=a}function Eb(a,b=-1){a=Db(a,b);a.Gg?.Jj?.(a);return a}function Fb(a,b){var c=void 0,d=c?null:a;c??=a.Fg.ih;Bb(c);try{c(d,b)}catch(e){if(e instanceof RangeError)throw new C(22);throw e;}}var Xa={open(a){a.Gg=nb[a.node.rdev].Gg;a.Gg.open?.(a)},bh(){throw new C(70);}};function Ta(a,b){nb[a]={Gg:b}}
function Gb(a,b){var c=b==="/";if(c&&mb)throw new C(10);if(!c&&b){var d=vb(b,{gi:!1});b=d.path;d=d.node;if(d.uh)throw new C(10);if(!E(d.mode))throw new C(54);}b={type:a,Sj:{},Mi:b,mj:[]};a=a.gh(b);a.gh=b;b.root=a;c?mb=a:d&&(d.uh=b,d.gh&&d.gh.mj.push(b))}function Hb(a,b,c){var d=vb(a,{parent:!0}).node;a=Ja(a);if(!a)throw new C(28);if(a==="."||a==="..")throw new C(20);var e=zb(d,a);if(e)throw new C(e);if(!d.Fg.Th)throw new C(63);return d.Fg.Th(d,a,b,c)}
function Ib(a,b=438){return Hb(a,b&4095|32768,0)}function I(a){return Hb(a,16895,0)}function Jb(a,b,c){typeof c=="undefined"&&(c=b,b=438);return Hb(a,b|8192,c)}function Kb(a,b){if(!Ma(a))throw new C(44);var c=vb(b,{parent:!0}).node;if(!c)throw new C(44);b=Ja(b);var d=zb(c,b);if(d)throw new C(d);if(!c.Fg.symlink)throw new C(63);c.Fg.symlink(c,b,a)}
function Lb(a){var b=vb(a,{parent:!0}).node;if(!b)throw new C(44);a=Ja(a);var c=Za(b,a),d=Ab(b,a,!1);if(d)throw new C(d);if(!b.Fg.unlink)throw new C(63);if(c.uh)throw new C(10);b.Fg.unlink(b,a);$a(c)}function Mb(a,b){a=vb(a,{Oh:!b}).node;return Bb(a.Fg.Xg)(a)}function Nb(a,b){a=typeof a=="string"?vb(a,{Oh:!0}).node:a;Fb(a,{mode:b&4095|a.mode&-4096,ctime:Date.now(),Ij:void 0})}
function Ob(a,b,c=438){if(a==="")throw new C(44);if(typeof b=="string"){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if(typeof d=="undefined")throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if(typeof a=="object")d=a;else{var e=a.endsWith("/");var f=vb(a,{Oh:!(b&131072),nj:!0});d=f.node;a=f.path}f=!1;if(b&64)if(d){if(b&128)throw new C(20);}else{if(e)throw new C(31);d=Hb(a,c|511,0);f=!0}if(!d)throw new C(44);(d.mode&61440)===8192&&(b&=-513);if(b&65536&&!E(d.mode))throw new C(54);
if(!f&&(d?(d.mode&61440)===40960?e=32:(e=["r","w","rw"][b&3],b&512&&(e+="w"),e=E(d.mode)&&(e!=="r"||b&576)?31:yb(d,e)):e=44,e))throw new C(e);if(b&512&&!f){e=d;e=typeof e=="string"?vb(e,{Oh:!0}).node:e;if(E(e.mode))throw new C(31);if((e.mode&61440)!==32768)throw new C(28);if(a=yb(e,"w"))throw new C(a);Fb(e,{size:0,timestamp:Date.now()})}b=Db({node:d,path:wb(d),flags:b&-131713,seekable:!0,position:0,Gg:d.Gg,sj:[],error:!1});b.Gg.open&&b.Gg.open(b);f&&Nb(d,c&511);return b}
function Pb(a){if(a.fd===null)throw new C(8);a.ji&&(a.ji=null);a.node?.oj();try{a.Gg.close&&a.Gg.close(a)}catch(b){throw b;}finally{ob[a.fd]=null}a.fd=null}function Qb(a,b,c){if(a.fd===null)throw new C(8);if(!a.seekable||!a.Gg.bh)throw new C(70);if(c!=0&&c!=1&&c!=2)throw new C(28);a.position=a.Gg.bh(a,b,c);a.sj=[]}
function Rb(a,b,c,d,e,f){if(d<0||e<0)throw new C(28);if(a.fd===null)throw new C(8);if((a.flags&2097155)===0)throw new C(8);if(E(a.node.mode))throw new C(31);if(!a.Gg.write)throw new C(28);a.seekable&&a.flags&1024&&Qb(a,0,2);var h=typeof e!="undefined";if(!h)e=a.position;else if(!a.seekable)throw new C(70);b=a.Gg.write(a,b,c,d,e,f);h||(a.position+=b);return b}
function Sb(){var a,b,c;rb=!0;a??=g.stdin;b??=g.stdout;c??=g.stderr;a?Tb("/dev","stdin",a):Kb("/dev/tty","/dev/stdin");b?Tb("/dev","stdout",null,b):Kb("/dev/tty","/dev/stdout");c?Tb("/dev","stderr",null,c):Kb("/dev/tty1","/dev/stderr");Ob("/dev/stdin",0);Ob("/dev/stdout",1);Ob("/dev/stderr",1)}function Ub(a,b){a=typeof a=="string"?a:wb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Ha(a+"/"+c);try{I(d)}catch(e){if(e.Ng!=20)throw e;}a=d}}return d}
function Vb(a,b,c,d){a=Ha((typeof a=="string"?a:wb(a))+"/"+b);return Ib(a,ab(c,d))}function Wb(a,b,c,d,e,f){var h=b;a&&(a=typeof a=="string"?a:wb(a),h=b?Ha(a+"/"+b):a);a=ab(d,e);h=Ib(h,a);c&&(typeof c=="string"&&(c=Qa(c)),c.subarray||(c=new Uint8Array(c)),Nb(h,a|146),b=Ob(h,577),Rb(b,c,0,c.length,0,f),Pb(b),Nb(h,a))}
function Tb(a,b,c,d){a=Ha((typeof a=="string"?a:wb(a))+"/"+b);b=ab(!!c,!!d);Tb.Ki??(Tb.Ki=64);var e=Tb.Ki++<<8|0;Ta(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,h,k,m){for(var n=0,q=0;q<m;q++){try{var w=c()}catch(z){throw new C(29);}if(w===void 0&&!n)throw new C(6);if(w===null||w===void 0)break;n++;h[k+q]=w}n&&(f.node.atime=Date.now());return n},write(f,h,k,m){for(var n=0;n<m;n++)try{d(h[k+n])}catch(q){throw new C(29);}m&&(f.node.mtime=f.node.ctime=Date.now());return n}});return Jb(a,
b,e)}function Xb(a){if(!(a.kj||a.lj||a.link||a.Ig))if(globalThis.XMLHttpRequest)y("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");else try{a.Ig=ka(a.url)}catch(b){throw new C(29);}}
function Yb(a,b,c,d,e){class f{eh=!1;Mg=[];Pg=void 0;Ah=0;ph=0;get(n){if(!(n>this.length-1||n<0)){var q=n%this.chunkSize;return this.Pg(n/this.chunkSize|0)[q]}}Jh(n){this.Pg=n}Bh(){var n=new XMLHttpRequest;n.open("HEAD",c,!1);n.send(null);n.status>=200&&n.status<300||n.status===304||y(`Couldn't load ${c}. Status: ${n.status}`);var q=Number(n.getResponseHeader("Content-length")),w,z=(w=n.getResponseHeader("Accept-Ranges"))&&w==="bytes";n=(w=n.getResponseHeader("Content-Encoding"))&&w==="gzip";var G=
1048576;z||(G=q);var F=this;F.Jh(L=>{var H=L*G,N=(L+1)*G-1;N=Math.min(N,q-1);if(typeof F.Mg[L]=="undefined"){var T=F.Mg;H>N&&y(`invalid range (${H}, ${N}) or no bytes requested!`);N>q-1&&y(`only ${q} bytes available! programmer error!`);var P=new XMLHttpRequest;P.open("GET",c,!1);q!==G&&P.setRequestHeader("Range",`bytes=${H}-${N}`);P.responseType="arraybuffer";P.overrideMimeType&&P.overrideMimeType("text/plain; charset=x-user-defined");P.send(null);P.status>=200&&P.status<300||P.status===304||y(`Couldn't load ${c}. Status: ${P.status}`);
H=P.response!==void 0?new Uint8Array(P.response||[]):Qa(P.responseText??"");T[L]=H}typeof F.Mg[L]=="undefined"&&y("doXHR failed!");return F.Mg[L]});if(n||!q)G=q=1,G=q=this.Pg(0).length,ma("LazyFiles on gzip forces download of the whole file when length is accessed");this.Ah=q;this.ph=G;this.eh=!0}get length(){this.eh||this.Bh();return this.Ah}get chunkSize(){this.eh||this.Bh();return this.ph}}if(globalThis.XMLHttpRequest){ba||y("Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc");
var h=new f;var k=void 0}else k=c,h=void 0;var m=Vb(a,b,d,e);h?m.Ig=h:k&&(m.Ig=null,m.url=k);Object.defineProperties(m,{Qg:{get:function(){return this.Ig.length}}});a={};for(let [n,q]of Object.entries(m.Gg))a[n]=(...w)=>{Xb(m);return q(...w)};a.read=(n,q,w,z,G)=>{Xb(m);n=n.node.Ig;if(G>=n.length)q=0;else{z=Math.min(n.length-G,z);if(n.slice)for(var F=0;F<z;F++)q[w+F]=n[G+F];else for(F=0;F<z;F++)q[w+F]=n.get(G+F);q=z}return q};a.oi=()=>{Xb(m);y();throw new C(48);};m.Gg=a;return m}
var J={},r,Zb=(a,b)=>a?A(r,a,b):"",u,ta;function $b(a,b,c){if(b.charAt(0)==="/")return b;a=a===-100?"/":Cb(a).path;if(b.length==0){if(!c)throw new C(44);return a}return a+"/"+b}
function bc(a,b){u[a>>2]=b.dev;u[a+4>>2]=b.mode;u[a+8>>2]=b.nlink;u[a+12>>2]=b.uid;u[a+16>>2]=b.gid;u[a+20>>2]=b.rdev;ta[a+24>>3]=BigInt(b.size);t[a+32>>2]=4096;t[a+36>>2]=b.blocks;var c=b.atime.getTime(),d=b.mtime.getTime(),e=b.ctime.getTime();ta[a+40>>3]=BigInt(Math.floor(c/1E3));u[a+48>>2]=c%1E3*1E3*1E3;ta[a+56>>3]=BigInt(Math.floor(d/1E3));u[a+64>>2]=d%1E3*1E3*1E3;ta[a+72>>3]=BigInt(Math.floor(e/1E3));u[a+80>>2]=e%1E3*1E3*1E3;ta[a+88>>3]=BigInt(b.ino);return 0}
var Ea=void 0,ra,cc=[],x,dc=(a,b)=>{cc.length=0;for(var c;c=r[a++];){var d=c!=105;d&=c!=112;b+=d&&b%8?4:0;cc.push(c==112?u[b>>2]:c==106?ta[b>>3]:c==105?t[b>>2]:x[b>>3]);b+=d?8:4}return cc},fc=(a,b,c)=>{b=dc(b,c);return ec[a](...b)},pc=(a,b)=>{hc=a;ic=b;if(!jc)return 1;if(a==0)kc=function(){setTimeout(lc,Math.max(0,mc+b-performance.now())|0)};else if(a==1)kc=function(){nc(lc)};else{if(!oc)if(globalThis.scheduler)oc=scheduler.postTask.bind(scheduler);else if(globalThis.setImmediate)oc=setImmediate;
else{var c=[];addEventListener("message",d=>{d.data==="setimmediate"&&(d.stopPropagation(),c.shift()())},!0);oc=d=>{c.push(d);ba?postMessage("setimmediate"):postMessage("setimmediate","*")}}kc=function(){oc(lc)}}return 0},qc=a=>{oa=a;Da||(g.onExit?.(a),na=!0);fa(a,new Ca(a))},rc=a=>{a instanceof Ca||a=="unwind"||fa(1,a)},sc=()=>{if(!Da)try{var a=oa;oa=a;qc(a)}catch(b){rc(b)}},Cc=(a,b,c,d,e)=>{function f(){return h<tc?(sc(),!1):!0}jc=a;uc=d;var h=tc;lc=function(){if(!na)if(vc.length>0){var k=vc.shift();
k.Nj(k.xj);if(wc){var m=wc,n=m%1==0?m-1:Math.floor(m);wc=k.Fj?n:(8*m+(n+.5))/9}g.setStatus&&(k=g.statusMessage||"Please wait...",m=wc??0,n=xc.Kj??0,m?m<n?g.setStatus("{message} ({expected - remaining}/{expected})"):g.setStatus(k):g.setStatus(""));f()&&setTimeout(lc,0)}else if(f())if(yc=yc+1|0,hc==1&&ic>1&&yc%ic!=0)kc();else{hc==0&&(mc=performance.now());a:if(!na){for(k of zc)if(k()===!1)break a;Ac(a);for(m of Bc)m()}f()&&kc()}};e||(b>0?pc(0,1E3/b):pc(1,1),kc());if(c)throw"unwind";},Ac=a=>{if(!na)try{a()}catch(b){rc(b)}finally{sc()}},
jc=null,kc=null,tc=0,uc=0,hc=0,ic=0,yc=0,vc=[],zc=[],Bc=[];function Dc(){kc&&(kc=null,tc++)}var Ec=0;function nc(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(Ec)for(;b+2>=Ec;)Ec+=1E3/60;else Ec=b+1E3/60;setTimeout(a,Math.max(Ec-b,0))}}var xc={},mc,lc,oc,wc;function Fc(a){var b=K.Sg[a];b.target.removeEventListener(b.Og,b.Ii,b.Ug);K.Sg.splice(a,1)}
function Gc(a,b,c){function d(f,h){if(f.length!=h.length)return!1;for(var k=0;k<f.length;k++)if(f[k]!=h[k])return!1;return!0}for(var e of K.kh)if(e.wi==a&&d(e.Ei,c))return;K.kh.push({wi:a,Oi:b,Ei:c});K.kh.sort((f,h)=>f.Oi-h.Oi)}function Hc(a){K.kh=K.kh.filter(b=>b.wi!=a)}function Ic(){return navigator.userActivation?navigator.userActivation.isActive:K.ki&&K.Vi.Di}function Jc(){if(Ic()){var a=K.kh;K.kh=[];for(var b of a)b.wi(...b.Ei)}}
function M(a){if(!a.target)return-4;if(a.Rg)a.Ii=function(c){++K.ki;K.Vi=a;Jc();a.Yg(c);Jc();--K.ki},a.target.addEventListener(a.Og,a.Ii,a.Ug),K.Sg.push(a);else for(var b=0;b<K.Sg.length;++b)K.Sg[b].target==a.target&&K.Sg[b].Og==a.Og&&Fc(b--);return 0}function Kc(a){return a==window?"#window":a==screen?"#screen":a?.nodeName??""}
var K={yj:0,ii:0,li:0,Qj:0,Ci:0,yi:0,fi:0,Gj:0,ri:0,Mh:0,hi:0,si:0,Bi:0,Xj:0,Uj(){for(;K.Sg.length;)Fc(K.Sg.length-1);K.kh=[]},ki:0,kh:[],Sg:[],qj:(a,b)=>{for(var c=0;c<K.Sg.length;++c)K.Sg[c].target!=a||b&&b!=K.Sg[c].Og||Fc(c--)},Vj(a){var b=!1;for(let c=0;c<K.Sg.length;++c){let d=K.Sg[c];d.target===a.target&&d.Tg===a.Tg&&d.Rg===a.Rg&&d.Vg===a.Vg&&(Fc(c--),b=!0)}return b?0:-5},fullscreenEnabled(){return document.fullscreenEnabled??document.webkitFullscreenEnabled}},Lc=[0,globalThis.document??0,globalThis.window??
0],O=a=>{a=a>2?a?A(r,a):"":a;return Lc[a]||globalThis.document?.querySelector(a)},Nc=a=>{var b=Pa(a)+1,c=Mc(b);B(a,r,c,b);return c},Qc=a=>{var b=Oc(),c=Mc(8),d=c+4;a=Nc(a.id);if(a=O(a))t[c>>2]=a.width,t[d>>2]=a.height;c=[t[c>>2],t[d>>2]];Pc(b);return c},Rc=(a,b,c)=>{a=O(a);if(!a)return-4;a.width=b;a.height=c;return 0},Sc=(a,b,c)=>{if(a.Ej){var d=Oc();a=Nc(a.id);Rc(a,b,c);Pc(d)}else a.width=b,a.height=c},Tc=0,Uc=[],Q=a=>{var b=Uc[a];b||(Uc[a]=b=Vc.get(a));return b},Wc=a=>{function b(){if(!(document.fullscreenElement??
document.webkitFullscreenElement)){document.removeEventListener("fullscreenchange",b);document.removeEventListener("webkitfullscreenchange",b);Sc(a,d,e);a.style.width=f;a.style.height=h;a.style.backgroundColor=k;m||(document.body.style.backgroundColor="white");document.body.style.backgroundColor=m;a.style.paddingLeft=n;a.style.paddingRight=q;a.style.paddingTop=w;a.style.paddingBottom=z;a.style.marginLeft=G;a.style.marginRight=F;a.style.marginTop=L;a.style.marginBottom=H;document.body.style.margin=
N;document.documentElement.style.overflow=T;document.body.scroll=P;a.style.imageRendering=qf;a.zh&&a.zh.jh.viewport(0,0,d,e);var ac=Tc;ac.Kh&&Q(ac.Kh)(37,0,ac.Fi)}}var c=Qc(a),d=c[0],e=c[1],f=a.style.width,h=a.style.height,k=a.style.backgroundColor,m=document.body.style.backgroundColor,n=a.style.paddingLeft,q=a.style.paddingRight,w=a.style.paddingTop,z=a.style.paddingBottom,G=a.style.marginLeft,F=a.style.marginRight,L=a.style.marginTop,H=a.style.marginBottom,N=document.body.style.margin,T=document.documentElement.style.overflow,
P=document.body.scroll,qf=a.style.imageRendering;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)},Xc=(a,b,c)=>{a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},Yc=a=>Lc.indexOf(a)<0?a.getBoundingClientRect():{left:0,top:0},Zc=(a,b)=>{if(b.ui!=0||b.Yh!=0){Wc(a);var c=b.rj?innerWidth:screen.width,d=b.rj?innerHeight:screen.height,e=Yc(a),f=e.width;e=e.height;var h=Qc(a),k=h[0];h=h[1];b.ui==3?(Xc(a,(d-
e)/2,(c-f)/2),c=f,d=e):b.ui==2&&(c*h<k*d?(f=h*c/k,Xc(a,(d-f)/2,0),d=f):(f=k*d/h,Xc(a,0,(c-f)/2),c=f));var m;(m=a.style).backgroundColor||(m.backgroundColor="black");let n;(n=document.body.style).backgroundColor||(n.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";b.cj==1&&(a.style.imageRendering="optimizeSpeed",a.style.imageRendering="-moz-crisp-edges",a.style.imageRendering="-o-crisp-edges",a.style.imageRendering="-webkit-optimize-contrast",a.style.imageRendering="optimize-contrast",
a.style.imageRendering="crisp-edges",a.style.imageRendering="pixelated");m=b.Yh==2?devicePixelRatio:1;b.Yh!=0&&(c=c*m|0,d=d*m|0,Sc(a,c,d),a.zh&&a.zh.jh.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return K.fullscreenEnabled()?-3:-1;Tc=b;b.Kh&&Q(b.Kh)(37,0,b.Fi);return 0},$c=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0},
ad=a=>{var b=document.fullscreenElement??document.webkitFullscreenElement,c=!!b;p[a]=c;p[a+1]=K.fullscreenEnabled();var d=c?b:K.pj,e=d?.id??"";B(Kc(d),r,a+2,128);B(e,r,a+130,128);t[a+260>>2]=d?.clientWidth??0;t[a+264>>2]=d?.clientHeight??0;t[a+268>>2]=screen.width;t[a+272>>2]=screen.height;c&&(K.pj=b)},bd=(a,b)=>{x[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)x[a+c*8+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)p[a+c+1040]=b.buttons[c].pressed,x[a+c*8+528>>3]=b.buttons[c].value;p[a+1104]=
b.connected;t[a+1108>>2]=b.index;t[a+8>>2]=b.axes.length;t[a+12>>2]=b.buttons.length;B(b.id,r,a+1112,64);B(b.mapping,r,a+1176,64)},cd=a=>{setTimeout(()=>{Ac(a)},1E4)},dd=!1,ed=[];
function kb(){function a(){dd=document.pointerLockElement===g.canvas}if(!fd){fd=!0;ib.push({canHandle:c=>!g.noImageDecoding&&/\.(jpg|jpeg|png|bmp|webp)$/i.test(c),handle:async(c,d)=>{var e=new Blob([c],{type:gd(d)});e.size!==c.length&&(e=new Blob([(new Uint8Array(c)).buffer],{type:gd(d)}));var f=URL.createObjectURL(e);return new Promise((h,k)=>{var m=new Image;m.onload=()=>{var n=document.createElement("canvas");n.width=m.width;n.height=m.height;n.getContext("2d").drawImage(m,0,0);URL.revokeObjectURL(f);
h(c)};m.onerror=()=>{l(`Image ${f} could not be decoded`);k()};m.src=f})}});ib.push({canHandle:c=>!g.noAudioDecoding&&c.slice(-4)in{".ogg":1,".wav":1,".mp3":1},handle:async(c,d)=>new Promise(e=>{function f(){h||(h=!0,e(c))}var h=!1,k=new Blob([c],{type:gd(d)});k=URL.createObjectURL(k);var m=new Audio;m.addEventListener("canplaythrough",()=>f(m));m.onerror=()=>{if(!h){l(`warning: browser could not fully decode audio ${d}, trying slower base64 approach`);var n="data:audio/x-"+d.slice(-3)+";base64,",
q="",w=0,z=0,G;for(G of c)for(w=w<<8|G,z+=8;z>=6;){var F=w>>z-6&63;z-=6;q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[F]}z==2?(q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(w&3)<<4],q+="=="):z==4&&(q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(w&15)<<2],q+="=");m.src=n+q;f(m)}};m.src=k;cd(()=>{f(m)})})});var b=g.canvas;b&&(document.addEventListener("pointerlockchange",a),g.elementPointerLock&&b.addEventListener("click",c=>{!dd&&
g.canvas.requestPointerLock&&(g.canvas.requestPointerLock(),c.preventDefault())}))}}function hd(a){a=a.getContext("2d");if(!a)return null;g.ctx=a;ed.forEach(b=>b());kb();return a}function gd(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.slice(a.lastIndexOf(".")+1)]}
var jb={},fd,R,jd=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,h)=>b.drawElementsInstancedANGLE(c,d,e,f,h))},kd=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>
b.isVertexArrayOES(c))},ld=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},md=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return a.getSupportedExtensions()?.filter(c=>b.includes(c))??[]},nd=(a,b,c,d)=>{var e=r;S.version>=2?c&&R.bufferSubData(a,b,e,d,c):R.bufferSubData(a,b,e.subarray(d,d+c))},od=1,pd=[],qd={},U=[],rd=[],sd=[],td=[],V=[],ud=[],vd=[],W=[],wd=[],xd=[],yd=[],zd=[1,1,2,2,4,4,4,2,3,4,8],Ad={},Bd={},Cd=4,Dd=0,Ed=a=>{for(var b=od++,c=a.length;c<b;c++)a[c]=null;for(;a[b];)b=od++;return b},Fd=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=R[c](),h=f&&Ed(d);f?(f.name=h,d[h]=f):X||=1282;t[b+e*4>>2]=h}},Gd=a=>{a=32-Math.clz32(a?
a-1:0);var b=S.xh[a];if(b)return b;b=R.getParameter(34965);S.xh[a]=R.createBuffer();R.bindBuffer(34963,S.xh[a]);R.bufferData(34963,1<<a,35048);R.bindBuffer(34963,b);return S.xh[a]},Id=a=>{Hd=!1;for(var b=0;b<S.mi;++b){var c=S.fh[b];if(c.rh&&c.enabled){Hd=!0;var d=c.size;var e=c.type,f=c.stride;d=f>0?a*f:d*zd[e-5120]*a;e=32-Math.clz32(d?d-1:0);f=S.yh[e];var h=S.mh[e];S.mh[e]=S.mh[e]+1&63;var k=f[h];k?e=k:(k=R.getParameter(34964),f[h]=R.createBuffer(),R.bindBuffer(34962,f[h]),R.bufferData(34962,1<<
e,35048),R.bindBuffer(34962,k),e=f[h]);R.bindBuffer(34962,e);nd(34962,0,d,c.Vh);c.Ai.call(R,b,c.size,c.type,c.pi,c.stride,0)}}},Kd=(a,b)=>{a.Jh||(a.Jh=a.getContext,a.getContext=function(d,e){e=a.Jh(d,e);return d=="webgl"==e instanceof WebGLRenderingContext?e:null});var c=b.Li>1?a.getContext("webgl2",b):a.getContext("webgl",b);return c?Jd(c,b):0},Jd=(a,b)=>{var c=Ed(vd),d={handle:c,attributes:b,version:b.Li,jh:a};a.canvas&&(a.canvas.zh=d);vd[c]=d;if(typeof b.Hi=="undefined"||b.Hi)if((a=d)||(a=S),!a.fj){a.fj=
!0;b=a.jh;b.Rj=b.getExtension("WEBGL_multi_draw");b.bj=b.getExtension("EXT_polygon_offset_clamp");b.aj=b.getExtension("EXT_clip_control");b.tj=b.getExtension("WEBGL_polygon_mode");jd(b);kd(b);ld(b);b.Hj=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.Oj=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");a.version>=2&&(b.Wg=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(a.version<2||!b.Wg)b.Wg=b.getExtension("EXT_disjoint_timer_query");for(var e of md(b))e.includes("lose_context")||
e.includes("debug")||b.getExtension(e)}d.mi=d.jh.getParameter(34921);d.fh=[];for(e=0;e<d.mi;e++)d.fh[e]={enabled:!1,rh:!1,size:0,type:0,pi:0,stride:0,Vh:0,Ai:null};d.mh=[];d.Wh=[];d.mh.length=d.Wh.length=22;d.yh=[];d.Hh=[];d.yh.length=d.Hh.length=22;d.xh=[];d.xh.length=22;for(e=0;e<=21;++e){d.xh[e]=null;d.mh[e]=d.Wh[e]=0;d.yh[e]=[];d.Hh[e]=[];a=d.yh[e];b=d.Hh[e];a.length=b.length=64;for(var f=0;f<64;++f)a[f]=b[f]=null}return c},S,X,Hd,Ld=a=>R.activeTexture(a),Md=(a,b)=>{R.attachShader(U[a],V[b])},
Nd=(a,b)=>{if(b&&!pd[b]){var c=R.createBuffer();c.name=b;pd[b]=c}a==34962?R.sh=b:a==34963&&(R.Dh=b);a==35051?R.$h=b:a==35052&&(R.ah=b);R.bindBuffer(a,pd[b])},Od=(a,b)=>{R.bindTexture(a,td[b])},Pd=a=>{R.bindVertexArray(ud[a]);a=R.getParameter(34965);R.Dh=a?a.name|0:0},Qd=(a,b)=>R.blendFunc(a,b),Rd=(a,b,c,d)=>{S.version>=2?c&&b?R.bufferData(a,r,d,c,b):R.bufferData(a,b,d):R.bufferData(a,c?r.subarray(c,c+b):b,d)},Sd=(a,b,c,d)=>nd(a,b,c,d),Td=a=>R.clear(a),v,Ud=(a,b,c,d)=>R.clearColor(a,b,c,d),Vd=a=>{R.compileShader(V[a])},
Wd=()=>{var a=Ed(U),b=R.createProgram();b.name=a;b.Sh=b.Qh=b.Rh=0;b.zi=1;U[a]=b;return a},Xd=a=>{var b=Ed(V);V[b]=R.createShader(a);return b},Yd=(a,b)=>{for(var c=0;c<a;c++){var d=t[b+c*4>>2],e=pd[d];e&&(R.deleteBuffer(e),e.name=0,pd[d]=null,d==R.sh&&(R.sh=0),d==R.Dh&&(R.Dh=0),d==R.$h&&(R.$h=0),d==R.ah&&(R.ah=0))}},Zd=a=>{if(a){var b=U[a];b?(R.deleteProgram(b),b.name=0,U[a]=null):X||=1281}},$d=a=>{if(a){var b=V[a];b?(R.deleteShader(b),V[a]=null):X||=1281}},ae=(a,b)=>{for(var c=0;c<a;c++){var d=t[b+
c*4>>2],e=td[d];e&&(R.deleteTexture(e),e.name=0,td[d]=null)}},be=(a,b)=>{for(var c=0;c<a;c++){var d=t[b+c*4>>2];R.deleteVertexArray(ud[d]);ud[d]=null}},ce=a=>R.disable(a),de=(a,b,c)=>{Id(b+c);R.drawArrays(a,b,c);Hd&&R.bindBuffer(34962,pd[R.sh])},ee=(a,b,c,d)=>{R.drawArraysInstanced(a,b,c,d)},fe=[],ge=(a,b)=>{for(var c=fe[a],d=0;d<a;d++)c[d]=t[b+d*4>>2];R.drawBuffers(c)},he=(a,b,c,d)=>{var e=0;if(!R.Dh){var f=1*zd[c-5120]*b;var h=Gd(f);R.bindBuffer(34963,h);nd(34963,0,f,d);if(b>0)for(h=0;h<S.mi;++h)if(f=
S.fh[h],f.rh&&f.enabled){switch(c){case 5121:e=Uint8Array;break;case 5123:e=Uint16Array;break;case 5125:e=Uint32Array;break;default:X||=1282;return}e=(new e(r.buffer,d,b)).reduce((k,m)=>Math.max(k,m))+1;break}d=0}Id(e);R.drawElements(a,b,c,d);Hd&&R.bindBuffer(34962,pd[R.sh]);R.Dh||R.bindBuffer(34963,null)},ie=(a,b,c,d,e)=>{R.drawElementsInstanced(a,b,c,d,e)},je=a=>R.enable(a),ke=a=>{S.fh[a].enabled=!0;R.enableVertexAttribArray(a)},le=a=>{switch(a){case 34962:a=34964;break;case 34963:a=34965;break;
case 35051:a=35053;break;case 35052:a=35055;break;case 35982:a=35983;break;case 36662:a=36662;break;case 36663:a=36663;break;case 35345:a=35368}return(a=R.getParameter(a))?a.name|0:0},me=a=>{switch(a){case 34962:case 34963:case 36662:case 36663:case 35051:case 35052:case 35882:case 35982:case 35345:return!0;default:return!1}},ne=(a,b)=>{Fd(a,b,"createBuffer",pd)},oe=(a,b)=>{Fd(a,b,"createTexture",td)},pe=(a,b)=>{Fd(a,b,"createVertexArray",ud)},qe=a=>R.generateMipmap(a),re=(a,b,c,d,e,f,h,k)=>{b=U[b];
if(a=R[a](b,c))d=k&&B(a.name,r,k,d),e&&(t[e>>2]=d),f&&(t[f>>2]=a.size),h&&(t[h>>2]=a.type)},se=(a,b)=>{u[a>>2]=b;u[a+4>>2]=(b-u[a>>2])/4294967296},te=()=>{var a=md(R);return a=a.concat(a.map(b=>"GL_"+b))},ue=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:c!=0&&c!=1&&(X||=1280);return;case 34814:case 36345:d=0;break;case 34466:var e=R.getParameter(34467);d=e?e.length:0;break;case 33309:if(S.version<2){X||=1282;return}d=te().length;break;case 33307:case 33308:if(S.version<2){X||=
1280;return}d=a==33307?3:0}if(d===void 0)switch(e=R.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":X||=1280;return;case "object":if(e===null)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:d=0;break;default:X||=1280;return}else{if(e instanceof Float32Array||e instanceof Uint32Array||
e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:t[b+a*4>>2]=e[a];break;case 2:v[b+a*4>>2]=e[a];break;case 4:p[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(f){X||=1280;l(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${f})`);return}}break;default:X||=1280;l(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);return}switch(c){case 1:se(b,d);break;case 0:t[b>>
2]=d;break;case 2:v[b>>2]=d;break;case 4:p[b]=d?1:0}}else X||=1281},ve=(a,b,c,d)=>{if(c){b=R.getIndexedParameter(a,b);switch(typeof b){case "boolean":a=b?1:0;break;case "number":a=b;break;case "object":if(b===null)switch(a){case 35983:case 35368:a=0;break;default:X||=1280;return}else if(b instanceof WebGLBuffer)a=b.name|0;else{X||=1280;return}break;default:X||=1280;return}switch(d){case 1:se(c,a);break;case 0:t[c>>2]=a;break;case 2:v[c>>2]=a;break;case 4:p[c]=a?1:0;break;default:y("internal emscriptenWebGLGetIndexed() error, bad type: "+
d)}}else X||=1281},we=(a,b,c)=>{if(c){a=W[a];b=S.version<2?R.Wg.getQueryObjectEXT(a,b):R.getQueryParameter(a,b);var d;typeof b=="boolean"?d=b?1:0:d=b;se(c,d)}else X||=1281},xe=(a,b,c)=>{if(c){a=R.Wg.getQueryObjectEXT(W[a],b);var d;typeof a=="boolean"?d=a?1:0:d=a;t[c>>2]=d}else X||=1281},ye=(a,b,c,d)=>{a=R.getShaderInfoLog(V[a]);a===null&&(a="(unknown error)");b=b>0&&d?B(a,r,d,b):0;c&&(t[c>>2]=b)},ze=(a,b,c)=>{c?b==35716?(a=R.getShaderInfoLog(V[a]),a===null&&(a="(unknown error)"),t[c>>2]=a?a.length+
1:0):b==35720?(a=R.getShaderSource(V[a]),t[c>>2]=a?a.length+1:0):t[c>>2]=R.getShaderParameter(V[a],b):X||=1281},Ae=a=>{var b=Pa(a)+1,c=Y(b);c&&B(a,r,c,b);return c},Be=a=>a.slice(-1)=="]"&&a.lastIndexOf("["),Ce=a=>{var b=a.Ih,c=a.Qi,d;if(!b){a.Ih=b={};a.Pi={};var e=R.getProgramParameter(a,35718);for(d=0;d<e;++d){var f=R.getActiveUniform(a,d);var h=f.name;f=f.size;var k=Be(h);k=k>0?h.slice(0,k):h;var m=a.zi;a.zi+=f;c[k]=[f,m];for(h=0;h<f;++h)b[m]=h,a.Pi[m++]=k}}},De=(a,b)=>{b=b?A(r,b):"";if(a=U[a]){Ce(a);
var c=a.Ih,d=0,e=b,f=Be(b);f>0&&(d=b.slice(f+1),d=parseInt(d)>>>0,e=b.slice(0,f));if((f=a.Qi[e])&&d<f[0]&&(d+=f[1],c[d]=c[d]||R.getUniformLocation(a,b)))return d}else X||=1281;return-1},Z=(a,b)=>{if(a){var c=a.Ih[b];typeof c=="number"&&(a.Ih[b]=c=R.getUniformLocation(a,a.Pi[b]+(c>0?`[${c}]`:"")));return c}X||=1282},Ee=(a,b,c,d)=>{if(c)if(a=U[a],Ce(a),a=R.getUniform(a,Z(a,b)),typeof a=="number"||typeof a=="boolean")switch(d){case 0:t[c>>2]=a;break;case 2:v[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:t[c+
b*4>>2]=a[b];break;case 2:v[c+b*4>>2]=a[b]}else X||=1281},Fe=(a,b,c,d)=>{if(c)if(S.fh[a].enabled&&l("glGetVertexAttrib*v on client-side array: not supported, bad data returned"),a=R.getVertexAttrib(a,b),b==34975)t[c>>2]=a&&a.name;else if(typeof a=="number"||typeof a=="boolean")switch(d){case 0:t[c>>2]=a;break;case 2:v[c>>2]=a;break;case 5:t[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:t[c+b*4>>2]=a[b];break;case 2:v[c+b*4>>2]=a[b];break;case 5:t[c+b*4>>2]=Math.fround(a[b])}else X||=
1281},Ge=(a,b,c)=>{Fe(a,b,c,0)},He=a=>R.isEnabled(a),Ie=a=>(a=ud[a])?R.isVertexArray(a):0,Je=a=>{a=U[a];R.linkProgram(a);a.Ih=0;a.Qi={}},Ke=(a,b)=>{a==3317?Cd=b:a==3314&&(Dd=b);R.pixelStorei(a,b)},sa,Le=a=>{a-=5120;return a==0?p:a==1?r:a==2?ra:a==4?t:a==6?v:a==5||a==28922||a==28520||a==30779||a==30782?u:sa},Me=(a,b,c,d,e)=>{a=Le(a);b=d*(({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*a.BYTES_PER_ELEMENT*(Dd||c)+Cd-1&-Cd);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),
e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},Ne=(a,b,c,d)=>{for(var e="",f=0;f<b;++f)e+=Zb(u[c+f*4>>2],d?u[d+f*4>>2]:void 0);R.shaderSource(V[a],e)},Oe=(a,b,c,d,e,f,h,k,m)=>{if(S.version>=2){if(R.ah){R.texImage2D(a,b,c,d,e,f,h,k,m);return}if(m){var n=Le(k);m>>>=31-Math.clz32(n.BYTES_PER_ELEMENT);R.texImage2D(a,b,c,d,e,f,h,k,n,m);return}}n=m?Me(k,h,d,e,m):null;R.texImage2D(a,b,c,d,e,f,h,k,n)},Pe=(a,b,c)=>R.texParameteri(a,b,c),Qe=[],Re=[],Se=(a,b,c)=>{R.uniform2f(Z(R.Eg,a),b,c)},Te=a=>{a=U[a];R.useProgram(a);
R.Eg=a},Ue=(a,b)=>{R.vertexAttribDivisor(a,b)},Ve=(a,b,c,d,e,f)=>{var h=S.fh[a];R.sh?(h.rh=!1,R.vertexAttribPointer(a,b,c,!!d,e,f)):(h.size=b,h.type=c,h.pi=d,h.stride=e,h.Vh=f,h.rh=!0,h.Ai=function(k,m,n,q,w,z){this.vertexAttribPointer(k,m,n,q,w,z)})},We=(a,b,c,d)=>R.viewport(a,b,c,d),Xe=(a,b)=>{if(!K.fullscreenEnabled())return-1;a=O(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?Ic()?Zc(a,b):b.Yi?(Gc(Zc,1,[a,b]),1):-2:-3:-4},Ye=()=>{try{if(navigator.getGamepads)return(K.Ph=navigator.getGamepads())?
0:-1}catch(a){navigator.getGamepads=null}return-1},Ze=(a,b)=>{var c={target:O(2),Og:"beforeunload",Tg:28,Vg:a,Rg:b,Yg:d=>{var e=Q(b)(28,0,a);e&&=e?A(r,e):"";if(e)return d.preventDefault(),d.returnValue=e},Ug:!0};return M(c)},$e=(a,b,c,d,e,f)=>{K.fi||(K.fi=Y(256));a={target:O(a),Og:f,Tg:e,Vg:b,Rg:d,Yg:h=>{var k=h.target.id??"",m=K.fi;B(Kc(h.target),r,m+0,128);B(k,r,m+128,128);Q(d)(e,m,b)&&h.preventDefault()},Ug:c};return M(a)},af=(a,b,c)=>{K.Mh||(K.Mh=Y(80));b={target:O(2),Og:"devicemotion",Tg:17,
Vg:a,Rg:c,Yg:d=>{var e=K.Mh,f=d.acceleration,h=d.accelerationIncludingGravity,k=d.rotationRate;var m=0|(f&&1)|(h&&2)|(k&&4);t[e+72>>2]=m;x[e>>3]=f?.x;x[e+8>>3]=f?.y;x[e+16>>3]=f?.z;x[e+24>>3]=h?.x;x[e+32>>3]=h?.y;x[e+40>>3]=h?.z;x[e+48>>3]=k?.alpha;x[e+56>>3]=k?.beta;x[e+64>>3]=k?.gamma;Q(c)(17,K.Mh,a)&&d.preventDefault()},Ug:b};return M(b)},bf=(a,b,c,d,e)=>{K.hi||(K.hi=Y(276));return M({target:a,Og:e,Tg:19,Vg:b,Rg:d,Yg:f=>{var h=K.hi;ad(h);Q(d)(19,h,b)&&f.preventDefault()},Ug:c})},cf=(a,b,c,d,e)=>
{K.ii||(K.ii=Y(1240));b={target:O(2),Di:!0,Og:e,Tg:d,Vg:a,Rg:c,Yg:f=>{var h=K.ii;bd(h,f.gamepad);Q(c)(d,h,a)&&f.preventDefault()},Ug:b};return M(b)},df=(a,b,c,d,e,f)=>{K.li||(K.li=Y(160));a={target:O(a),Og:f,Tg:e,Vg:b,Rg:d,Yg:h=>{var k=K.li;x[k>>3]=h.timeStamp;var m=k>>2;t[m+2]=h.location;p[k+12]=h.ctrlKey;p[k+13]=h.shiftKey;p[k+14]=h.altKey;p[k+15]=h.metaKey;p[k+16]=h.repeat;t[m+5]=h.charCode;t[m+6]=h.keyCode;t[m+7]=h.which;B(h.key??"",r,k+32,32);B(h.code??"",r,k+64,32);B(h.char??"",r,k+96,32);B(h.locale??
"",r,k+128,32);Q(d)(e,k,b)&&h.preventDefault()},Ug:c};return M(a)},ef=(a,b,c)=>{var d=screen.orientation;K.ri||(K.ri=Y(8));return M({target:d,Og:"change",Tg:18,Vg:a,Rg:c,Yg:e=>{var f=K.ri,h=["portrait-primary","portrait-secondary","landscape-primary","landscape-secondary"],k=["portrait","portrait","landscape","landscape"],m=0,n=window.screen?.orientation;n?(m=h.indexOf(n.type),m<0&&(m=k.indexOf(n.type)),m>=0&&(m=1<<m),h=n.angle):h=window.orientation;t[f>>2]=m;t[f+4>>2]=h;Q(c)(18,f,a)&&e.preventDefault()},
Ug:b})},ff=(a,b,c,d)=>{K.si||(K.si=Y(257));return M({target:a,Og:"pointerlockchange",Tg:20,Vg:b,Rg:d,Yg:e=>{var f=K.si,h=document.pointerLockElement;p[f]=!!h;var k=h?.id??"";B(Kc(h),r,f+1,128);B(k,r,f+129,128);Q(d)(20,f,b)&&e.preventDefault()},Ug:c})},gf=(a,b,c,d)=>{K.yi||(K.yi=Y(36));a=O(a);return M({target:a,Og:"resize",Tg:10,Vg:b,Rg:d,Yg:e=>{if(e.target==a){var f=document.body;if(f){var h=K.yi;t[h>>2]=0;t[h+4>>2]=f.clientWidth;t[h+8>>2]=f.clientHeight;t[h+12>>2]=innerWidth;t[h+16>>2]=innerHeight;
t[h+20>>2]=outerWidth;t[h+24>>2]=outerHeight;t[h+28>>2]=pageXOffset|0;t[h+32>>2]=pageYOffset|0;Q(d)(10,h,b)&&e.preventDefault()}}},Ug:c})},hf=(a,b,c)=>{var d=Lc[1];K.Bi||(K.Bi=Y(8));return M({target:d,Og:"visibilitychange",Tg:21,Vg:a,Rg:c,Yg:e=>{var f=K.Bi,h=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);p[f]=document.hidden;t[f+4>>2]=h;Q(c)(21,f,a)&&e.preventDefault()},Ug:b})},jf=(a,b,c,d)=>{K.Ci||(K.Ci=Y(96));return M({target:a,Di:!0,Og:"wheel",Tg:9,Vg:b,Rg:d,Yg:e=>
{var f=K.Ci;x[f>>3]=e.timeStamp;var h=f>>2;t[h+2]=e.screenX;t[h+3]=e.screenY;t[h+4]=e.clientX;t[h+5]=e.clientY;p[f+24]=e.ctrlKey;p[f+25]=e.shiftKey;p[f+26]=e.altKey;p[f+27]=e.metaKey;ra[h*2+14]=e.button;ra[h*2+15]=e.buttons;t[h+8]=e.movementX;t[h+9]=e.movementY;var k=Yc(a);t[h+10]=e.clientX-(k.left|0);t[h+11]=e.clientY-(k.top|0);x[f+64>>3]=e.deltaX;x[f+72>>3]=e.deltaY;x[f+80>>3]=e.deltaZ;t[f+88>>2]=e.deltaMode;Q(d)(9,f,b)&&e.preventDefault()},Ug:c})},kf=["default","low-power","high-performance"],
lf={},nf=()=>{if(!mf){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:ea},b;for(b in lf)lf[b]===void 0?delete a[b]:a[b]=lf[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);mf=c}return mf},mf,of=a=>{for(var b of["keydown","mousedown","touchstart"])for(var c of[document,document.getElementById("canvas")])c?.addEventListener(b,()=>{a.state==="suspended"&&a.resume()},{once:!0})},pf=(a,b=[])=>{Q(a)(...b)};
function rf(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":p[a]=b;break;case "i8":p[a]=b;break;case "i16":ra[a>>1]=b;break;case "i32":t[a>>2]=b;break;case "i64":ta[a>>3]=BigInt(b);break;case "float":v[a>>2]=b;break;case "double":x[a>>3]=b;break;case "*":u[a>>2]=b;break;default:y(`invalid type for setValue: ${c}`)}}qb=Array(4096);Gb(D,"/");I("/tmp");I("/home");I("/home/web_user");
(function(){I("/dev");Ta(259,{read:()=>0,write:(d,e,f,h)=>h,bh:()=>0});Jb("/dev/null",259);Sa(1280,Va);Sa(1536,Wa);Jb("/dev/tty",1280);Jb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{b||(La(a),b=a.byteLength);return a[--b]};Tb("/dev","random",c);Tb("/dev","urandom",c);I("/dev/shm");I("/dev/shm/tmp")})();
(function(){I("/proc");var a=I("/proc/self");I("/proc/self/fd");Gb({gh(){var b=Ya(a,"fd",16895,73);b.Gg={bh:D.Gg.bh};b.Fg={lookup(c,d){c=+d;var e=Cb(c);c={parent:null,gh:{Mi:"fake"},Fg:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(ob.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();g.requestAnimationFrame=nc;g.pauseMainLoop=Dc;g.resumeMainLoop=function(){tc++;var a=hc,b=ic,c=jc;jc=null;Cc(c,0,!1,uc,!0);pc(a,b);kc()};
var sf=()=>{if(S){var a=S.yh;S.yh=S.Hh;S.Hh=a;a=S.mh;S.mh=S.Wh;S.Wh=a;for(a=0;a<=21;++a)S.mh[a]=0}};typeof xc!="undefined"&&zc.push(sf);for(let a=0;a<32;++a)fe.push(Array(a));for(var tf=new Float32Array(288),uf=0;uf<=288;++uf)Qe[uf]=tf.subarray(0,uf);var vf=new Int32Array(288);for(uf=0;uf<=288;++uf)Re[uf]=vf.subarray(0,uf);g.noExitRuntime&&(Da=g.noExitRuntime);g.print&&(ma=g.print);g.printErr&&(l=g.printErr);g.arguments&&(da=g.arguments);g.thisProgram&&(ea=g.thisProgram);var wf=g.preInit;
if(wf)for(typeof wf=="function"&&(g.preInit=wf=[wf]);wf.length>0;)wf.shift()();g.addRunDependency=hb;g.removeRunDependency=gb;g.FS_preloadFile=async(a,b,c,d,e,f,h,k)=>{var m=b?Ma(Ha(a+"/"+b)):a,n=`cp ${m}`;hb(n);try{var q=c;typeof c=="string"&&(q=await bb(c));q=await lb(q,m);k?.();f||Wb(a,b,q,d,e,h)}finally{gb(n)}};g.FS_unlink=(...a)=>Lb(...a);g.FS_createPath=(...a)=>Ub(...a);g.FS_createDevice=(...a)=>Tb(...a);g.FS_createDataFile=(...a)=>Wb(...a);g.FS_createLazyFile=(...a)=>Yb(...a);
var ec={332652:()=>{typeof g.SDL3==="undefined"&&(g.SDL3={});var a=g.SDL3;typeof a.qh==="undefined"&&(a.qh=function(b){return b});typeof a.Xh==="undefined"&&(a.Xh=function(b){return b>>>2})},332966:a=>{a=(a?A(r,a):"")+"\n\nAbort/Retry/Ignore/AlwaysIgnore? [ariA] :";a=window.prompt(a,"i");a===null&&(a="i");return a.length===1?a.charCodeAt(0):-1},333181:()=>{g.SDL3.Eh={};g.SDL3.Eh.nh=[];g.SDL3.Eh.nh[0]=void 0;g.SDL3.Eh.nh[1]=void 0},333358:(a,b,c,d,e)=>{var f=g.SDL3.Eh;f.nh[a]!==void 0&&clearInterval(f.nh[a]);
f.nh[a]=setInterval(function(){pf(d,[e])},b/c*1E3)},333550:a=>{var b=g.SDL3.Eh;b.nh[a]!==void 0&&clearInterval(b.nh[a]);b.nh[a]=void 0},333681:()=>typeof AudioContext!=="undefined"||typeof webkitAudioContext!=="undefined"?!0:!1,333828:()=>typeof navigator.mediaDevices!=="undefined"&&typeof navigator.mediaDevices.getUserMedia!=="undefined"||typeof navigator.webkitGetUserMedia!=="undefined"?!0:!1,334062:()=>{var a=g.SDL3;typeof a.Kg==="undefined"&&(a.Kg={});typeof a.Hg==="undefined"&&(a.Hg={});a.Lg||
(typeof AudioContext!=="undefined"?a.Lg=new AudioContext:typeof webkitAudioContext!=="undefined"&&(a.Lg=new webkitAudioContext),a.Lg&&typeof navigator.userActivation==="undefined"&&of(a.Lg));return a.Lg!==void 0},334641:()=>g.SDL3.Lg.sampleRate,334692:(a,b,c,d)=>{function e(){}function f(k){h.Hg.$g!==void 0&&(clearInterval(h.Hg.$g),h.Hg.$g=void 0,h.Hg.oh=void 0);h.Hg.ni=h.Lg.createMediaStreamSource(k);h.Hg.Zg=h.Lg.createScriptProcessor(b,a,1);h.Hg.Zg.onaudioprocess=function(m){h!==void 0&&h.Hg!==
void 0&&(m.outputBuffer.getChannelData(0).fill(0),h.Hg.ai=m.inputBuffer,pf(c,[d]))};h.Hg.ni.connect(h.Hg.Zg);h.Hg.Zg.connect(h.Lg.destination);h.Hg.stream=k}var h=g.SDL3;h.Hg.oh=h.Lg.createBuffer(a,b,h.Lg.sampleRate);h.Hg.oh.getChannelData(0).fill(0);h.Hg.$g=setInterval(function(){h.Hg.ai=h.Hg.oh;pf(c,[d])},b/h.Lg.sampleRate*1E3);navigator.mediaDevices!==void 0&&navigator.mediaDevices.getUserMedia!==void 0?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):navigator.webkitGetUserMedia!==
void 0&&navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},336533:(a,b,c,d)=>{var e=g.SDL3;e.Kg.Zg=e.Lg.createScriptProcessor(b,0,a);e.Kg.Zg.onaudioprocess=function(f){e!==void 0&&e.Kg!==void 0&&(e.Kg.$g!==void 0&&(clearInterval(e.Kg.$g),e.Kg.$g=void 0,e.Kg.oh=void 0),e.Kg.Lh=f.outputBuffer,pf(c,[d]))};e.Kg.Zg.connect(e.Lg.destination);e.Lg.state==="suspended"&&(e.Kg.oh=e.Lg.createBuffer(a,b,e.Lg.sampleRate),e.Kg.oh.getChannelData(0).fill(0),e.Kg.$g=setInterval(function(){typeof navigator.userActivation!==
"undefined"&&navigator.userActivation.hasBeenActive&&e.Lg.resume();e.Kg.Lh=e.Kg.oh;pf(c,[d]);e.Kg.Lh=void 0},b/e.Lg.sampleRate*1E3))},337849:a=>{var b=g.SDL3;if(a){b.Hg.$g!==void 0&&clearInterval(b.Hg.$g);if(b.Hg.stream!==void 0){a=b.Hg.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.Hg.stream.removeTrack(a[c])}b.Hg.Zg!==void 0&&(b.Hg.Zg.onaudioprocess=function(){},b.Hg.Zg.disconnect());b.Hg.ni!==void 0&&b.Hg.ni.disconnect();b.Hg=void 0}else b.Kg.Zg!=void 0&&b.Kg.Zg.disconnect(),b.Kg.$g!==void 0&&
clearInterval(b.Kg.$g),b.Kg=void 0;b.Lg!==void 0&&b.Kg===void 0&&b.Hg===void 0&&(b.Lg.close(),b.Lg=void 0)},339005:(a,b)=>{var c=g.SDL3;a=c.Xh(a);for(var d=c.Kg.Lh.numberOfChannels,e=0;e<d;++e){var f=c.Kg.Lh.getChannelData(e);if(f.length!=b)throw"Web Audio playback buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var h=0;h<b;++h)f[h]=v[a+(h*d+e)]}},339538:(a,b)=>{for(var c=g.SDL3,d=c.Hg.ai.numberOfChannels,e=0;e<d;++e){var f=c.Hg.ai.getChannelData(e);
if(f.length!=b)throw"Web Audio recording buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";if(d==1)for(var h=0;h<b;++h)rf(a+h*4,f[h]);else for(h=0;h<b;++h)rf(a+(h*d+e)*4,f[h])}},340165:()=>{g.SDL3.Jg={}},340197:()=>navigator.mediaDevices===void 0?0:1,340256:(a,b,c,d,e)=>{function f(){var n=g.SDL3;if(typeof n!=="undefined"&&typeof n.Jg!=="undefined"&&typeof n.Jg.stream!=="undefined"){var q=performance.now();if(q>=n.Jg.Uh)for(m(h);n.Jg.Uh<q;)n.Jg.Uh+=n.Jg.dj;
requestAnimationFrame(f)}}var h=a,k=g.uj,m=g.vj;a={};b<=0||c<=0?a.video=!0:(a.video={},a.video.width=b,a.video.height=c);d>0&&e>0&&(a.video.frameRate={ideal:d/e});navigator.mediaDevices.getUserMedia(a).then(n=>{var q=n.getVideoTracks()[0].getSettings(),w=q.width,z=q.height;q=q.frameRate;console.log("Camera is opened! Actual spec: ("+w+"x"+z+"), fps="+q);if(k(h,1,w,z,q)){let G=document.createElement("video");G.width=w;G.height=z;G.style.display="none";G.srcObject=n;let F=document.createElement("canvas");
F.width=w;F.height=z;F.style.display="none";let L=F.getContext("2d"),H=g.SDL3;H.Jg.width=w;H.Jg.height=z;H.Jg.Lj=q;H.Jg.dj=1E3/q;H.Jg.stream=n;H.Jg.video=G;H.Jg.canvas=F;H.Jg.Zh=L;H.Jg.Uh=performance.now();G.play();G.addEventListener("loadedmetadata",()=>{f()})}}).catch(n=>{console.error("Tried to open camera but it threw an error! "+n.name+": "+n.message);k(h,0,0,0,0)})},342562:()=>{var a=g.SDL3;typeof a!=="undefined"&&typeof a.Jg!=="undefined"&&typeof a.Jg.stream!=="undefined"&&(a.Jg.stream.getTracks().forEach(b=>
b.stop()),a.Jg={})},342813:(a,b,c)=>{var d=g.SDL3;if(typeof d==="undefined"||typeof d.Jg==="undefined"||typeof d.Jg.Zh==="undefined")return 0;d.Jg.Zh.drawImage(d.Jg.video,0,0,a,b);a=d.Jg.Zh.getImageData(0,0,a,b).data;r.set(a,c);return 1},343191:()=>{typeof g.SDL3!=="undefined"&&(g.SDL3.Jg=void 0)},343278:a=>{var b=navigator.getGamepads();return b?(a=b[a])&&a.vibrationActuator?1:0:0},343453:(a,b,c)=>{var d=navigator.getGamepads();if(!d)return 0;a=d[a];if(!a||!a.vibrationActuator)return 0;a.vibrationActuator.playEffect("dual-rumble",
{startDelay:0,duration:3E3,weakMagnitude:c/65535,strongMagnitude:b/65535});return 1},343789:(a,b,c,d)=>{d=d?A(r,d):"";var e=document.querySelector(d);d=g.SDL3;if(d.Ui!==e){d.Ch=hd(e);if(!d.Ch)return!1;d.Ui=e}if(d.w!==a||d.h!==b||d.ej!==d.Ch)d.image=d.Ch.createImageData(a,b),d.w=a,d.h=b,d.ej=d.Ch;a=d.image.data;c/=4;d.Xi!==a&&(d.Wi=new Int32Array(a.buffer),d.Xi=a);a=d.Wi;a.set(t.subarray(c,c+a.length));d.Ch.putImageData(d.image,0,0);return!0},344538:()=>{var a=g.SDL3;a.mouse_x=0;a.mouse_y=0;a.mouse_buttons=
[];for(var b=0;b<5;++b)a.mouse_buttons[b]=!1;document.addEventListener("mousemove",function(c){var d=g.SDL3;d.mouse_x=c.clientX;d.mouse_y=c.clientY});document.addEventListener("mousedown",function(c){var d=g.SDL3;0<=c.button&&c.button<d.mouse_buttons.length&&(d.mouse_buttons[c.button]=!0)});document.addEventListener("mouseup",function(c){var d=g.SDL3;0<=c.button&&c.button<d.mouse_buttons.length&&(d.mouse_buttons[c.button]=!1)})},345226:(a,b,c,d,e)=>{var f=document.createElement("canvas");f.width=
a;f.height=b;var h=f.getContext("2d");a=h.createImageData(a,b);e/=4;b=new Int32Array(a.data.buffer);b.set(t.subarray(e,e+b.length));h.putImageData(a,0,0);c=c===0&&d===0?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=xf(c.length+1);B(c,r,d,c.length+1);return d},345884:a=>{g.canvas&&(g.canvas.style.cursor=a?A(r,a):"")},345967:()=>{g.canvas&&(g.canvas.style.cursor="none")},346036:()=>g.SDL3.mouse_x,346074:()=>g.SDL3.mouse_y,346112:a=>g.SDL3.mouse_buttons[a],346160:a=>{document.Pg=
function(b){b.key!="CapsLock"&&b.key!="NumLock"&&b.key!="ScrollLock"&&yf(g.SDL3.qh(a),b.getModifierState("CapsLock"),b.getModifierState("NumLock"),b.getModifierState("ScrollLock"))};document.addEventListener("keydown",document.Pg)},346587:()=>{document.removeEventListener("keydown",document.Pg)},346671:a=>{var b=document;b&&(b.Mg=function(c){var d=g.SDL3;c=d.Gh(0,0,c);c!=0&&(zf(d.qh(a),c),Af(c))},b.addEventListener("pointerup",b.Mg))},347032:a=>{var b=g.SDL3;b.Gh===void 0&&(b.Gh=function(c,d,e){if(e.pointerType==
"mouse")var f=1;else if(e.pointerType=="touch")f=2;else if(e.pointerType=="pen")f=3;else return 0;var h=xf(a);if(h!=0){var k=b.Xh(h);t[k++]=f;t[k++]=e.pointerId;t[k++]=typeof e.button!=="undefined"?e.button:-1;t[k++]=e.buttons;t[k++]=e.type=="pointerdown"?1:0;v[k++]=e.movementX;v[k++]=e.movementY;v[k++]=e.clientX-c;v[k++]=e.clientY-d;f==3&&(v[k++]=e.pressure,v[k++]=e.tangentialPressure,v[k++]=e.tiltX,v[k++]=e.tiltY,v[k++]=e.twist)}return h})},348024:a=>{a=a?A(r,a):"";try{var b=document.querySelector(a);
if(b)return b===document.activeElement}catch(c){}return!1},348190:()=>document.hasFocus(),348222:()=>{var a=document;a&&(a.removeEventListener("pointerup",a.Mg),a.Mg=void 0)},348404:()=>document.body.clientWidth,348442:()=>document.body.clientHeight,348481:()=>window.innerWidth,348511:()=>window.innerHeight,348542:()=>window.outerWidth,348572:()=>window.outerHeight,348603:()=>window.pageXOffset,348634:()=>window.pageYOffset,348665:(a,b)=>{var c=document.querySelector(b?A(r,b):"");if(c){var d=g.SDL3;
c.ph=function(e){var f=c.getBoundingClientRect();e=d.Gh(f.left,f.top,e);e!=0&&(Bf(d.qh(a),e),Af(e))};c.eh=function(e){var f=c.getBoundingClientRect();e=d.Gh(f.left,f.top,e);e!=0&&(Cf(d.qh(a),e),Af(e))};c.Pg=function(e){var f=c.getBoundingClientRect();e=d.Gh(f.left,f.top,e);e!=0&&(Df(d.qh(a),e),Af(e))};c.style.touchAction="none";c.addEventListener("pointerenter",c.ph);c.addEventListener("pointerleave",c.eh);c.addEventListener("pointercancel",c.eh);c.addEventListener("pointerdown",c.Pg);c.addEventListener("pointermove",
c.Pg);c.addEventListener("pointerup",c.Pg)}},350053:(a,b,c)=>{var d=document.querySelector(b?A(r,b):"");if(d){var e=g.SDL3,f=function(h){var k=xf(c);if(k!=0){var m=k>>2,n=d.getBoundingClientRect();t[m++]=h.clientX-n.left;t[m++]=h.clientY-n.top}return k};e.ci=function(h){h.preventDefault();h=f(h);h!=0&&(Ef(a,h),Af(h))};d.addEventListener("dragover",e.ci);e.Nh=0;try{I("/tmp/filedrop")}catch(h){}e.di=function(h){h.preventDefault();if(h.dataTransfer.types.includes("text/plain"))h=Ae(h.dataTransfer.getData("text/plain")),
Ff(a,h),Gf(h);else if(h.dataTransfer.types.includes("Files")){let k=0,m=h.dataTransfer.files.length;for(let n=0;n<m;n++){let q=h.dataTransfer.files.item(n),w=new FileReader;w.readAsArrayBuffer(q);w.onload=function(z){var G=`/tmp/filedrop/${e.Nh}`;e.Nh+=1;var F=`${G}/${q.name}`,L=Ae(F);z=new Uint8Array(z.target.result);try{I(G);var H=Ob(F,"w");Rb(H,z,0,z.length,0);Pb(H);Hf(a,L)}catch(N){}Gf(L);++k;k===m&&If(a)};w.onerror=function(){++k;k===m&&If(a)}}}If(a)};d.addEventListener("drop",e.di);e.Fh=function(h){h.preventDefault();
If(a)};d.addEventListener("dragend",e.Fh);d.addEventListener("dragleave",e.Fh)}},352420:a=>{if(a=document.querySelector(a?A(r,a):"")){var b=g.SDL3;a.removeEventListener("dragleave",b.Fh);a.removeEventListener("dragend",b.Fh);a.removeEventListener("drop",b.di);b.Nh=void 0;"/tmp/filedrop";var c=vb("/tmp/filedrop",{parent:!0}).node,d=Ja("/tmp/filedrop"),e=Za(c,d),f=Ab(c,d,!0);if(f)throw new C(f);if(!c.Fg.rmdir)throw new C(63);if(e.uh)throw new C(10);c.Fg.rmdir(c,d);$a(e);a.removeEventListener("dragover",
b.ci);b.ci=void 0;b.di=void 0;b.Fh=void 0}},353250:a=>{if(a=document.querySelector(a?A(r,a):""))a.removeEventListener("pointerenter",a.ph),a.removeEventListener("pointerleave",a.eh),a.removeEventListener("pointercancel",a.eh),a.removeEventListener("pointerdown",a.Pg),a.removeEventListener("pointermove",a.Pg),a.removeEventListener("pointerup",a.Pg),a.style.touchAction="",a.ph=void 0,a.eh=void 0,a.Pg=void 0},353984:()=>window.matchMedia?window.matchMedia("(prefers-color-scheme: light)").matches?0:window.matchMedia("(prefers-color-scheme: dark)").matches?
1:-1:-1,354193:()=>{if(typeof g.SDL3!=="undefined"){var a=g.SDL3;a.xi.removeEventListener("change",a.ei);a.xi=void 0;a.ei=void 0}},354446:()=>window.innerWidth,354476:()=>window.innerHeight,354507:a=>{g.requestFullscreen=function(){Jf(a)}},354616:(a,b)=>{a=r.buffer instanceof ArrayBuffer?r.subarray(a,a+b):r.slice(a,a+b);a=URL.createObjectURL(new Blob([a],{type:"image/png"}));b=document.querySelector("link[rel~='icon']");b||(b=document.createElement("link"),b.rel="icon",b.type="image/png",document.head.appendChild(b));
b.href&&b.href.startsWith("blob:")&&URL.revokeObjectURL(b.href);b.href=a},355109:()=>{g.requestFullscreen=function(){}},355183:()=>window.innerWidth,355213:()=>window.innerHeight,355244:a=>{a=document.querySelector(a?A(r,a):"");a.Si=a.style.position;a.Ti=a.style.top;a.Ri=a.style.left;var b=document.createElement("div");b.id="SDL3_fill_document_background_elements";b.Mg=a;b.Bh=a.parentNode;b.Ah=a.nextSibling;var c=Array.from(document.body.children),d;for(d of c)b.appendChild(d);document.body.appendChild(b);
b.style.display="none";document.body.appendChild(a);a.style.position="fixed";a.style.top="0";a.style.left="0"},355942:()=>{var a=document.getElementById("SDL3_fill_document_background_elements");if(a){for(a.Ah?a.Bh.insertBefore(a.Mg,a.Ah):a.Bh.appendChild(a.Mg);a.firstChild;)document.body.insertBefore(a.firstChild,a);a.Mg.style.position=a.Mg.Si;a.Mg.style.top=a.Mg.Ti;a.Mg.style.left=a.Mg.Ri;a.remove()}},356501:()=>{if(window.matchMedia){var a=g.SDL3;a.ei=function(){Kf()};a.xi=window.matchMedia("(prefers-color-scheme: dark)");
a.xi.addEventListener("change",a.ei)}},356823:(a,b,c,d,e)=>{a=a?A(r,a):"";b=b?A(r,b):"";c=c?A(r,c):"";d=d?A(r,d):"";var f=e?A(r,e):"";e=document.createElement("dialog");e.classList.add("SDL3_messagebox");e.id=f;e.style.color=d;e.style.backgroundColor=c;document.body.append(e);d=document.createElement("h1");d.innerText=a;e.append(d);a=document.createElement("p");a.innerText=b;e.append(a);e.showModal()},357364:(a,b,c,d,e,f,h,k)=>{a=a?A(r,a):"";b=b?A(r,b):"";f=f?A(r,f):"";var m=h?A(r,h):"",n=k?A(r,k):
"",q=document.getElementById(a);if(!q)return!1;var w=document.createElement("button");w.innerText=b;w.style.borderColor=f;w.style.backgroundColor=m;q.addEventListener("keydown",function(z){d&&z.key==="Enter"?(z.preventDefault(),w.click()):e&&z.key==="Escape"&&(z.preventDefault(),w.click())});q.addEventListener("cancel",function(z){z.preventDefault()});w.onmouseenter=function(){w.style.backgroundColor=n};w.onmouseleave=function(){w.style.backgroundColor=m};w.onclick=function(){q.close(c)};q.append(w);
return!0},358373:a=>{a=a?A(r,a):"";return(a=document.getElementById(a))?a.open:!1},358511:a=>{a=a?A(r,a):"";a=document.getElementById(a);if(!a)return 0;try{return parseInt(a.returnValue)}catch(b){return 0}},358693:(a,b)=>{alert((a?A(r,a):"")+"\n\n"+(b?A(r,b):""))}},Lf,Y,Mf,Af,xf,Gf,Bf,Cf,Df,zf,Ef,If,Ff,Hf,yf,Kf,Jf,Pc,Mc,Oc,qa,Vc,Nf={Ra:function(a){a=navigator.getGamepads()[a];if(a.id.indexOf("Product: ")>0){let b=a.id.indexOf("Product: ")+9;return parseInt(a.id.substr(b,4),16)}a=a.id.split("-");return a.length>
1&&!isNaN(parseInt(a[1],16))?parseInt(a[1],16):0},Sa:function(a){a=navigator.getGamepads()[a];if(a.id.indexOf("Vendor: ")>0){let b=a.id.indexOf("Vendor: ")+8;return parseInt(a.id.substr(b,4),16)}a=a.id.split("-");return a.length>1&&!isNaN(parseInt(a[0],16))?parseInt(a[0],16):0},Qa:function(a){return navigator.getGamepads()[a].id.toLowerCase().indexOf("xinput")>=0},ja:function(a,b,c){Ea=c;try{var d=Cb(a);switch(b){case 0:var e=Fa();if(e<0)break;for(;ob[e];)e++;return Eb(d,e).fd;case 1:case 2:return 0;
case 3:return d.flags;case 4:return e=Fa(),d.flags=d.flags&-289793|e&289792,0;case 12:return e=Fa(),ra[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if(typeof J=="undefined"||f.name!=="ErrnoError")throw f;return-f.Ng}},db:function(a){try{return Cb(a),0}catch(b){if(typeof J=="undefined"||b.name!=="ErrnoError")throw b;return-b.Ng}},$a:function(a,b){try{var c=Cb(a),d=c.node,e=c.Gg.Xg;a=e?c:d;e??=d.Fg.Xg;Bb(e);var f=e(a);return bc(b,f)}catch(h){if(typeof J=="undefined"||h.name!=="ErrnoError")throw h;
return-h.Ng}},bb:function(a,b,c){Ea=c;try{var d=Cb(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.hh.hj){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=Fa();t[e>>2]=25856;t[e+4>>2]=5;t[e+8>>2]=191;t[e+12>>2]=35387;for(var f=0;f<32;f++)p[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.hh.ij)for(e=Fa(),a=[],f=0;f<32;f++)a.push(p[e+f+17]);
return 0;case 21519:if(!d.tty)return-59;e=Fa();return t[e>>2]=0;case 21520:return d.tty?-28:-59;case 21537:case 21531:e=Fa();if(!d.Gg.gj)throw new C(59);return d.Gg.gj(d,b,e);case 21523:if(!d.tty)return-59;d.tty.hh.jj&&(f=[24,80],e=Fa(),ra[e>>1]=f[0],ra[e+2>>1]=f[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(h){if(typeof J=="undefined"||h.name!=="ErrnoError")throw h;return-h.Ng}},Ya:function(a,b){try{return a=a?A(r,a):"",bc(b,Mb(a,!0))}catch(c){if(typeof J==
"undefined"||c.name!=="ErrnoError")throw c;return-c.Ng}},Za:function(a,b,c,d){try{b=b?A(r,b):"";var e=d&256;b=$b(a,b,d&4096);return bc(c,e?Mb(b,!0):Mb(b))}catch(f){if(typeof J=="undefined"||f.name!=="ErrnoError")throw f;return-f.Ng}},cb:function(a,b,c,d){Ea=d;try{b=b?A(r,b):"";b=$b(a,b);var e=d?Fa():0;c&64&&(e&=-19);return Ob(b,c,e).fd}catch(f){if(typeof J=="undefined"||f.name!=="ErrnoError")throw f;return-f.Ng}},_a:function(a,b){try{return a=a?A(r,a):"",bc(b,Mb(a))}catch(c){if(typeof J=="undefined"||
c.name!=="ErrnoError")throw c;return-c.Ng}},fb:()=>y(""),_:fc,p:(a,b,c)=>{b=dc(b,c);return ec[a](...b)},a:fc,La:(a,b,c)=>{b=dc(b,c);return ec[a](...b)},Ua:()=>{Dc();jc=null},eb:()=>Date.now(),Ga:()=>{if(!K.fullscreenEnabled())return-1;Hc(Zc);var a=Lc[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},Ka:()=>{Hc($c);if(!document.exitPointerLock)return-1;document.exitPointerLock();
return 0},o:()=>globalThis.devicePixelRatio??1,g:(a,b,c)=>{a=O(a);if(!a)return-4;a=Yc(a);x[b>>3]=a.width;x[c>>3]=a.height;return 0},Ia:a=>{if(!K.fullscreenEnabled())return-1;ad(a);return 0},fa:(a,b)=>{if(a<0||a>=K.Ph.length)return-5;if(!K.Ph[a])return-7;bd(b,K.Ph[a]);return 0},Oa:(a,b)=>{a&&(t[a>>2]=hc);b&&(t[b>>2]=ic)},ha:()=>performance.now(),Ta:()=>K.Ph.length,Ma:(a,b)=>{t[a>>2]=screen.width;t[b>>2]=screen.height},_f:Ld,Zf:Md,$c:(a,b)=>{R.beginQuery(a,W[b])},Ca:(a,b)=>{R.Wg.beginQueryEXT(a,W[b])},
Ec:a=>R.beginTransformFeedback(a),Yf:(a,b,c)=>{R.bindAttribLocation(U[a],b,c?A(r,c):"")},Xf:Nd,Bc:(a,b,c)=>{R.bindBufferBase(a,b,pd[c])},Cc:(a,b,c,d,e)=>{R.bindBufferRange(a,b,pd[c],d,e)},Wf:(a,b)=>{R.bindFramebuffer(a,rd[b])},Vf:(a,b)=>{R.bindRenderbuffer(a,sd[b])},Jb:(a,b)=>{R.bindSampler(a,wd[b])},Uf:Od,Bb:(a,b)=>{R.bindTransformFeedback(a,xd[b])},Jc:Pd,ua:Pd,Tf:(a,b,c,d)=>R.blendColor(a,b,c,d),Sf:a=>R.blendEquation(a),Rf:(a,b)=>R.blendEquationSeparate(a,b),Qf:Qd,Pf:(a,b,c,d)=>R.blendFuncSeparate(a,
b,c,d),Oc:(a,b,c,d,e,f,h,k,m,n)=>R.blitFramebuffer(a,b,c,d,e,f,h,k,m,n),Of:Rd,Nf:Sd,Mf:a=>R.checkFramebufferStatus(a),Lf:Td,ec:(a,b,c,d)=>R.clearBufferfi(a,b,c,d),fc:(a,b,c)=>{R.clearBufferfv(a,b,v,c>>2)},hc:(a,b,c)=>{R.clearBufferiv(a,b,t,c>>2)},gc:(a,b,c)=>{R.clearBufferuiv(a,b,u,c>>2)},Kf:Ud,Jf:a=>R.clearDepth(a),If:a=>R.clearStencil(a),Sb:(a,b,c)=>{c=Number(c);return R.clientWaitSync(yd[a],b,c)},pd:(a,b)=>{R.aj.clipControlEXT(a,b)},Hf:(a,b,c,d)=>{R.colorMask(!!a,!!b,!!c,!!d)},Gf:Vd,Ff:(a,b,c,
d,e,f,h,k)=>{S.version>=2?R.ah||!h?R.compressedTexImage2D(a,b,c,d,e,f,h,k):R.compressedTexImage2D(a,b,c,d,e,f,r,k,h):R.compressedTexImage2D(a,b,c,d,e,f,r.subarray(k,k+h))},ed:(a,b,c,d,e,f,h,k,m)=>{R.ah?R.compressedTexImage3D(a,b,c,d,e,f,h,k,m):R.compressedTexImage3D(a,b,c,d,e,f,h,r,m,k)},Ef:(a,b,c,d,e,f,h,k,m)=>{S.version>=2?R.ah||!k?R.compressedTexSubImage2D(a,b,c,d,e,f,h,k,m):R.compressedTexSubImage2D(a,b,c,d,e,f,h,r,m,k):R.compressedTexSubImage2D(a,b,c,d,e,f,h,r.subarray(m,m+k))},dd:(a,b,c,d,e,
f,h,k,m,n,q)=>{R.ah?R.compressedTexSubImage3D(a,b,c,d,e,f,h,k,m,n,q):R.compressedTexSubImage3D(a,b,c,d,e,f,h,k,m,r,q,n)},cc:(a,b,c,d,e)=>R.copyBufferSubData(a,b,c,d,e),Df:(a,b,c,d,e,f,h,k)=>R.copyTexImage2D(a,b,c,d,e,f,h,k),Cf:(a,b,c,d,e,f,h,k)=>R.copyTexSubImage2D(a,b,c,d,e,f,h,k),fd:(a,b,c,d,e,f,h,k,m)=>R.copyTexSubImage3D(a,b,c,d,e,f,h,k,m),Bf:Wd,Af:Xd,zf:a=>R.cullFace(a),yf:Yd,xf:(a,b)=>{for(var c=0;c<a;++c){var d=t[b+c*4>>2],e=rd[d];e&&(R.deleteFramebuffer(e),e.name=0,rd[d]=null)}},wf:Zd,bd:(a,
b)=>{for(var c=0;c<a;c++){var d=t[b+c*4>>2],e=W[d];e&&(R.deleteQuery(e),W[d]=null)}},Ea:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+c*4>>2],e=W[d];e&&(R.Wg.deleteQueryEXT(e),W[d]=null)}},vf:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+c*4>>2],e=sd[d];e&&(R.deleteRenderbuffer(e),e.name=0,sd[d]=null)}},Lb:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+c*4>>2],e=wd[d];e&&(R.deleteSampler(e),e.name=0,wd[d]=null)}},uf:$d,Tb:a=>{if(a){var b=yd[a];b?(R.deleteSync(b),b.name=0,yd[a]=null):X||=1281}},tf:ae,Ab:(a,b)=>{for(var c=
0;c<a;c++){var d=t[b+c*4>>2],e=xd[d];e&&(R.deleteTransformFeedback(e),e.name=0,xd[d]=null)}},Ic:be,ta:be,sf:a=>R.depthFunc(a),rf:a=>{R.depthMask(!!a)},qf:(a,b)=>R.depthRange(a,b),pf:(a,b)=>{R.detachShader(U[a],V[b])},of:ce,nf:a=>{S.fh[a].enabled=!1;R.disableVertexAttribArray(a)},mf:de,Xb:ee,bg:ee,kb:ee,md:ee,lb:ee,Vc:ge,kd:ge,qa:ge,lf:he,Wb:ie,ag:ie,ib:ie,jb:ie,ld:ie,id:(a,b,c,d,e,f)=>{he(a,d,e,f)},kf:je,jf:ke,_c:a=>R.endQuery(a),Ba:a=>{R.Wg.endQueryEXT(a)},Dc:()=>R.endTransformFeedback(),Vb:(a,b)=>
(a=R.fenceSync(a,b))?(b=Ed(yd),a.name=b,yd[b]=a,b):0,hf:()=>R.finish(),gf:()=>R.flush(),Kc:(a,b,c)=>{if(me(a)){var d=qd[le(a)];d?d.access&16?b<0||c<0||b+c>d.length?(X||=1281,l("invalid range in glFlushMappedBufferRange")):nd(a,d.offset,c,d.th+b):(X||=1282,l("buffer was not mapped with GL_MAP_FLUSH_EXPLICIT_BIT in glFlushMappedBufferRange")):(X||=1282,l("buffer was never mapped in glFlushMappedBufferRange"))}else X||=1280,l("GL_INVALID_ENUM in glFlushMappedBufferRange")},ff:(a,b,c,d)=>{R.framebufferRenderbuffer(a,
b,c,sd[d])},ef:(a,b,c,d,e)=>{R.framebufferTexture2D(a,b,c,td[d],e)},Mc:(a,b,c,d,e)=>{R.framebufferTextureLayer(a,b,td[c],d,e)},df:a=>R.frontFace(a),cf:ne,af:(a,b)=>{Fd(a,b,"createFramebuffer",rd)},cd:(a,b)=>{Fd(a,b,"createQuery",W)},Fa:(a,b)=>{for(var c=0;c<a;c++){var d=R.Wg.createQueryEXT();if(!d){for(X||=1282;c<a;)t[b+c++*4>>2]=0;break}var e=Ed(W);d.name=e;W[e]=d;t[b+c*4>>2]=e}},$e:(a,b)=>{Fd(a,b,"createRenderbuffer",sd)},Mb:(a,b)=>{Fd(a,b,"createSampler",wd)},_e:oe,zb:(a,b)=>{Fd(a,b,"createTransformFeedback",
xd)},Hc:pe,sa:pe,bf:qe,Ze:(a,b,c,d,e,f,h)=>re("getActiveAttrib",a,b,c,d,e,f,h),Ye:(a,b,c,d,e,f,h)=>re("getActiveUniform",a,b,c,d,e,f,h),Zb:(a,b,c,d,e)=>{a=U[a];if(a=R.getActiveUniformBlockName(a,b))e&&c>0?(c=B(a,r,e,c),d&&(t[d>>2]=c)):d&&(t[d>>2]=0)},_b:(a,b,c,d)=>{if(d)if(a=U[a],c==35393)t[d>>2]=R.getActiveUniformBlockName(a,b).length+1;else{if(a=R.getActiveUniformBlockParameter(a,b,c),a!==null)if(c==35395)for(c=0;c<a.length;c++)t[d+c*4>>2]=a[c];else t[d>>2]=a}else X||=1281},ac:(a,b,c,d,e)=>{if(e)if(b>
0&&c==0)X||=1281;else{a=U[a];for(var f=[],h=0;h<b;h++)f.push(t[c+h*4>>2]);if(a=R.getActiveUniforms(a,f,d))for(b=a.length,h=0;h<b;h++)t[e+h*4>>2]=a[h]}else X||=1281},Xe:(a,b,c,d)=>{a=R.getAttachedShaders(U[a]);var e=a.length;e>b&&(e=b);t[c>>2]=e;for(b=0;b<e;++b)t[d+b*4>>2]=V.indexOf(a[b])},We:(a,b)=>R.getAttribLocation(U[a],b?A(r,b):""),Ve:(a,b)=>ue(a,b,4),Nb:(a,b,c)=>{c?se(c,R.getBufferParameter(a,b)):X||=1281},Ue:(a,b,c)=>{c?t[c>>2]=R.getBufferParameter(a,b):X||=1281},Wc:(a,b,c)=>{if(b==35005){b=
0;if(a=qd[le(a)])b=a.th;t[c>>2]=b}else X||=1280,l("GL_INVALID_ENUM in glGetBufferPointerv")},Te:()=>{var a=R.getError()||X;X=0;return a},Se:(a,b)=>ue(a,b,2),qc:(a,b)=>R.getFragDataLocation(U[a],b?A(r,b):""),Re:(a,b,c,d)=>{a=R.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;t[d>>2]=a},Ob:(a,b,c)=>ve(a,b,c,1),Qb:(a,b)=>{ue(a,b,1)},Fc:(a,b,c)=>ve(a,b,c,0),Qe:(a,b)=>ue(a,b,0),ob:(a,b,c,d,e)=>{if(d<0)X||=1281;else if(e){if(a=R.getInternalformatParameter(a,
b,c),a!==null)for(b=0;b<a.length&&b<d;++b)t[e+b*4>>2]=a[b]}else X||=1281},vb:()=>{X||=1282},Oe:(a,b,c,d)=>{a=R.getProgramInfoLog(U[a]);a===null&&(a="(unknown error)");b=b>0&&d?B(a,r,d,b):0;c&&(t[c>>2]=b)},Pe:(a,b,c)=>{if(c)if(a>=od)X||=1281;else if(a=U[a],b==35716)a=R.getProgramInfoLog(a),a===null&&(a="(unknown error)"),t[c>>2]=a.length+1;else if(b==35719){if(!a.Sh){var d=R.getProgramParameter(a,35718);for(b=0;b<d;++b)a.Sh=Math.max(a.Sh,R.getActiveUniform(a,b).name.length+1)}t[c>>2]=a.Sh}else if(b==
35722){if(!a.Qh)for(d=R.getProgramParameter(a,35721),b=0;b<d;++b)a.Qh=Math.max(a.Qh,R.getActiveAttrib(a,b).name.length+1);t[c>>2]=a.Qh}else if(b==35381){if(!a.Rh)for(d=R.getProgramParameter(a,35382),b=0;b<d;++b)a.Rh=Math.max(a.Rh,R.getActiveUniformBlockName(a,b).length+1);t[c>>2]=a.Rh}else t[c>>2]=R.getProgramParameter(a,b);else X||=1281},wa:we,ya:xe,va:we,Yc:(a,b,c)=>{if(c){a=R.getQueryParameter(W[a],b);var d;typeof a=="boolean"?d=a?1:0:d=a;t[c>>2]=d}else X||=1281},xa:xe,Zc:(a,b,c)=>{c?t[c>>2]=R.getQuery(a,
b):X||=1281},za:(a,b,c)=>{c?t[c>>2]=R.Wg.getQueryEXT(a,b):X||=1281},Ne:(a,b,c)=>{c?t[c>>2]=R.getRenderbufferParameter(a,b):X||=1281},Db:(a,b,c)=>{c?v[c>>2]=R.getSamplerParameter(wd[a],b):X||=1281},Eb:(a,b,c)=>{c?t[c>>2]=R.getSamplerParameter(wd[a],b):X||=1281},Le:ye,Ke:(a,b,c,d)=>{a=R.getShaderPrecisionFormat(a,b);t[c>>2]=a.rangeMin;t[c+4>>2]=a.rangeMax;t[d>>2]=a.precision},Je:(a,b,c,d)=>{if(a=R.getShaderSource(V[a]))b=b>0&&d?B(a,r,d,b):0,c&&(t[c>>2]=b)},Me:ze,Ie:a=>{var b=Ad[a];if(!b){switch(a){case 7939:b=
Ae(te().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=R.getParameter(a))||(X||=1280);b=b?Ae(b):0;break;case 7938:b=R.getParameter(7938);var c=`OpenGL ES 2.0 (${b})`;S.version>=2&&(c=`OpenGL ES 3.0 (${b})`);b=Ae(c);break;case 35724:b=R.getParameter(35724);c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);c!==null&&(c[1].length==3&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=Ae(b);break;default:X||=1280}Ad[a]=b}return b},dc:(a,b)=>{if(S.version<2)return X||=1282,0;var c=
Bd[a];if(c)return b<0||b>=c.length?(X||=1281,0):c[b];switch(a){case 7939:return c=te().map(Ae),c=Bd[a]=c,b<0||b>=c.length?(X||=1281,0):c[b];default:return X||=1280,0}},Pb:(a,b,c,d,e)=>{c<0?X||=1281:e?(a=R.getSyncParameter(yd[a],b),a!==null&&(t[e>>2]=a,d&&(t[d>>2]=1))):X||=1281},He:(a,b,c)=>{c?v[c>>2]=R.getTexParameter(a,b):X||=1281},Ge:(a,b,c)=>{c?t[c>>2]=R.getTexParameter(a,b):X||=1281},zc:(a,b,c,d,e,f,h)=>{a=U[a];if(a=R.getTransformFeedbackVarying(a,b))h&&c>0?(c=B(a.name,r,h,c),d&&(t[d>>2]=c)):
d&&(t[d>>2]=0),e&&(t[e>>2]=a.size),f&&(t[f>>2]=a.type)},$b:(a,b)=>R.getUniformBlockIndex(U[a],b?A(r,b):""),bc:(a,b,c,d)=>{if(d)if(b>0&&(c==0||d==0))X||=1281;else{a=U[a];for(var e=[],f=0;f<b;f++)e.push(Zb(u[c+f*4>>2]));if(a=R.getUniformIndices(a,e))for(b=a.length,f=0;f<b;f++)t[d+f*4>>2]=a[f]}else X||=1281},De,Fe:(a,b,c)=>{Ee(a,b,c,2)},Ee:(a,b,c)=>{Ee(a,b,c,0)},rc:(a,b,c)=>Ee(a,b,c,0),xc:Ge,wc:Ge,Ae:(a,b,c)=>{c?(S.fh[a].enabled&&l("glGetVertexAttribPointer on client-side array: not supported, bad data returned"),
t[c>>2]=R.getVertexAttribOffset(a,b)):X||=1281},Ce:(a,b,c)=>{Fe(a,b,c,2)},Be:(a,b,c)=>{Fe(a,b,c,5)},ze:(a,b)=>R.hint(a,b),sb:(a,b,c)=>{for(var d=fe[b],e=0;e<b;e++)d[e]=t[c+e*4>>2];R.invalidateFramebuffer(a,d)},rb:(a,b,c,d,e,f,h)=>{for(var k=fe[b],m=0;m<b;m++)k[m]=t[c+m*4>>2];R.invalidateSubFramebuffer(a,k,d,e,f,h)},ye:a=>(a=pd[a])?R.isBuffer(a):0,xe:He,we:a=>(a=rd[a])?R.isFramebuffer(a):0,ve:a=>(a=U[a])?R.isProgram(a):0,ad:a=>(a=W[a])?R.isQuery(a):0,Da:a=>(a=W[a])?R.Wg.isQueryEXT(a):0,ue:a=>(a=sd[a])?
R.isRenderbuffer(a):0,Kb:a=>(a=wd[a])?R.isSampler(a):0,te:a=>(a=V[a])?R.isShader(a):0,Ub:a=>R.isSync(yd[a]),se:a=>(a=td[a])?R.isTexture(a):0,yb:a=>R.isTransformFeedback(xd[a]),Gc:Ie,ra:Ie,re:a=>R.lineWidth(a),qe:Je,Lc:(a,b,c,d)=>{if((d&33)!=0)return l("glMapBufferRange access does not support MAP_READ or MAP_UNSYNCHRONIZED"),0;if((d&2)==0)return l("glMapBufferRange access must include MAP_WRITE"),0;if((d&12)==0)return l("glMapBufferRange access must include INVALIDATE_BUFFER or INVALIDATE_RANGE"),
0;if(!me(a))return X||=1280,l("GL_INVALID_ENUM in glMapBufferRange"),0;var e=Y(c);a=le(a);if(!e)return 0;var f;a=qd[f=a]??(qd[f]={});a.offset=b;a.length=c;a.th=e;a.access=d;return e},xb:()=>R.pauseTransformFeedback(),pe:Ke,od:(a,b)=>{R.tj.polygonModeWEBGL(a,b)},oe:(a,b)=>R.polygonOffset(a,b),qd:(a,b,c)=>{R.bj.polygonOffsetClampEXT(a,b,c)},ub:()=>{X||=1280},tb:()=>{X||=1280},Aa:(a,b)=>{R.Wg.queryCounterEXT(W[a],b)},jd:a=>R.readBuffer(a),ne:(a,b,c,d,e,f,h)=>{if(S.version>=2)if(R.$h)R.readPixels(a,b,
c,d,e,f,h);else{var k=Le(f);h>>>=31-Math.clz32(k.BYTES_PER_ELEMENT);R.readPixels(a,b,c,d,e,f,k,h)}else(k=Me(f,e,c,d,h))?R.readPixels(a,b,c,d,e,f,k):X||=1280},me:()=>{},le:(a,b,c,d)=>R.renderbufferStorage(a,b,c,d),Nc:(a,b,c,d,e)=>R.renderbufferStorageMultisample(a,b,c,d,e),wb:()=>R.resumeTransformFeedback(),ke:(a,b)=>{R.sampleCoverage(a,!!b)},Gb:(a,b,c)=>{R.samplerParameterf(wd[a],b,c)},Fb:(a,b,c)=>{R.samplerParameterf(wd[a],b,v[c>>2])},Ib:(a,b,c)=>{R.samplerParameteri(wd[a],b,c)},Hb:(a,b,c)=>{R.samplerParameteri(wd[a],
b,t[c>>2])},je:(a,b,c,d)=>R.scissor(a,b,c,d),he:()=>{X||=1280},ge:Ne,fe:(a,b,c)=>R.stencilFunc(a,b,c),ee:(a,b,c,d)=>R.stencilFuncSeparate(a,b,c,d),de:a=>R.stencilMask(a),ce:(a,b)=>R.stencilMaskSeparate(a,b),be:(a,b,c)=>R.stencilOp(a,b,c),ae:(a,b,c,d)=>R.stencilOpSeparate(a,b,c,d),$d:Oe,hd:(a,b,c,d,e,f,h,k,m,n)=>{if(R.ah)R.texImage3D(a,b,c,d,e,f,h,k,m,n);else if(n){var q=Le(m);R.texImage3D(a,b,c,d,e,f,h,k,m,q,n>>>31-Math.clz32(q.BYTES_PER_ELEMENT))}else R.texImage3D(a,b,c,d,e,f,h,k,m,null)},_d:(a,
b,c)=>R.texParameterf(a,b,c),Zd:(a,b,c)=>{R.texParameterf(a,b,v[c>>2])},Yd:Pe,Xd:(a,b,c)=>{R.texParameteri(a,b,t[c>>2])},qb:(a,b,c,d,e)=>R.texStorage2D(a,b,c,d,e),pb:(a,b,c,d,e,f)=>R.texStorage3D(a,b,c,d,e,f),Wd:(a,b,c,d,e,f,h,k,m)=>{if(S.version>=2){if(R.ah){R.texSubImage2D(a,b,c,d,e,f,h,k,m);return}if(m){var n=Le(k);R.texSubImage2D(a,b,c,d,e,f,h,k,n,m>>>31-Math.clz32(n.BYTES_PER_ELEMENT));return}}m=m?Me(k,h,e,f,m):null;R.texSubImage2D(a,b,c,d,e,f,h,k,m)},gd:(a,b,c,d,e,f,h,k,m,n,q)=>{if(R.ah)R.texSubImage3D(a,
b,c,d,e,f,h,k,m,n,q);else if(q){var w=Le(n);R.texSubImage3D(a,b,c,d,e,f,h,k,m,n,w,q>>>31-Math.clz32(w.BYTES_PER_ELEMENT))}else R.texSubImage3D(a,b,c,d,e,f,h,k,m,n,null)},Ac:(a,b,c,d)=>{a=U[a];for(var e=[],f=0;f<b;f++)e.push(Zb(u[c+f*4>>2]));R.transformFeedbackVaryings(a,e,d)},Vd:(a,b)=>{R.uniform1f(Z(R.Eg,a),b)},Ud:(a,b,c)=>{if(S.version>=2)b&&R.uniform1fv(Z(R.Eg,a),v,c>>2,b);else{if(b<=288)for(var d=Qe[b],e=0;e<b;++e)d[e]=v[c+4*e>>2];else d=v.subarray(c>>2,c+b*4>>2);R.uniform1fv(Z(R.Eg,a),d)}},Td:(a,
b)=>{R.uniform1i(Z(R.Eg,a),b)},Sd:(a,b,c)=>{if(S.version>=2)b&&R.uniform1iv(Z(R.Eg,a),t,c>>2,b);else{if(b<=288)for(var d=Re[b],e=0;e<b;++e)d[e]=t[c+4*e>>2];else d=t.subarray(c>>2,c+b*4>>2);R.uniform1iv(Z(R.Eg,a),d)}},pc:(a,b)=>{R.uniform1ui(Z(R.Eg,a),b)},lc:(a,b,c)=>{b&&R.uniform1uiv(Z(R.Eg,a),u,c>>2,b)},Rd:Se,Qd:(a,b,c)=>{if(S.version>=2)b&&R.uniform2fv(Z(R.Eg,a),v,c>>2,b*2);else{if(b<=144){b*=2;for(var d=Qe[b],e=0;e<b;e+=2)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2]}else d=v.subarray(c>>2,c+b*8>>2);
R.uniform2fv(Z(R.Eg,a),d)}},Pd:(a,b,c)=>{R.uniform2i(Z(R.Eg,a),b,c)},Od:(a,b,c)=>{if(S.version>=2)b&&R.uniform2iv(Z(R.Eg,a),t,c>>2,b*2);else{if(b<=144){b*=2;for(var d=Re[b],e=0;e<b;e+=2)d[e]=t[c+4*e>>2],d[e+1]=t[c+(4*e+4)>>2]}else d=t.subarray(c>>2,c+b*8>>2);R.uniform2iv(Z(R.Eg,a),d)}},oc:(a,b,c)=>{R.uniform2ui(Z(R.Eg,a),b,c)},kc:(a,b,c)=>{b&&R.uniform2uiv(Z(R.Eg,a),u,c>>2,b*2)},Nd:(a,b,c,d)=>{R.uniform3f(Z(R.Eg,a),b,c,d)},Md:(a,b,c)=>{if(S.version>=2)b&&R.uniform3fv(Z(R.Eg,a),v,c>>2,b*3);else{if(b<=
96){b*=3;for(var d=Qe[b],e=0;e<b;e+=3)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2]}else d=v.subarray(c>>2,c+b*12>>2);R.uniform3fv(Z(R.Eg,a),d)}},Ld:(a,b,c,d)=>{R.uniform3i(Z(R.Eg,a),b,c,d)},Kd:(a,b,c)=>{if(S.version>=2)b&&R.uniform3iv(Z(R.Eg,a),t,c>>2,b*3);else{if(b<=96){b*=3;for(var d=Re[b],e=0;e<b;e+=3)d[e]=t[c+4*e>>2],d[e+1]=t[c+(4*e+4)>>2],d[e+2]=t[c+(4*e+8)>>2]}else d=t.subarray(c>>2,c+b*12>>2);R.uniform3iv(Z(R.Eg,a),d)}},nc:(a,b,c,d)=>{R.uniform3ui(Z(R.Eg,a),b,c,d)},jc:(a,
b,c)=>{b&&R.uniform3uiv(Z(R.Eg,a),u,c>>2,b*3)},Jd:(a,b,c,d,e)=>{R.uniform4f(Z(R.Eg,a),b,c,d,e)},Id:(a,b,c)=>{if(S.version>=2)b&&R.uniform4fv(Z(R.Eg,a),v,c>>2,b*4);else{if(b<=72){var d=Qe[4*b],e=v;c>>=2;b*=4;for(var f=0;f<b;f+=4){var h=c+f;d[f]=e[h];d[f+1]=e[h+1];d[f+2]=e[h+2];d[f+3]=e[h+3]}}else d=v.subarray(c>>2,c+b*16>>2);R.uniform4fv(Z(R.Eg,a),d)}},Hd:(a,b,c,d,e)=>{R.uniform4i(Z(R.Eg,a),b,c,d,e)},Gd:(a,b,c)=>{if(S.version>=2)b&&R.uniform4iv(Z(R.Eg,a),t,c>>2,b*4);else{if(b<=72){b*=4;for(var d=Re[b],
e=0;e<b;e+=4)d[e]=t[c+4*e>>2],d[e+1]=t[c+(4*e+4)>>2],d[e+2]=t[c+(4*e+8)>>2],d[e+3]=t[c+(4*e+12)>>2]}else d=t.subarray(c>>2,c+b*16>>2);R.uniform4iv(Z(R.Eg,a),d)}},mc:(a,b,c,d,e)=>{R.uniform4ui(Z(R.Eg,a),b,c,d,e)},ic:(a,b,c)=>{b&&R.uniform4uiv(Z(R.Eg,a),u,c>>2,b*4)},Yb:(a,b,c)=>{a=U[a];R.uniformBlockBinding(a,b,c)},Fd:(a,b,c,d)=>{if(S.version>=2)b&&R.uniformMatrix2fv(Z(R.Eg,a),!!c,v,d>>2,b*4);else{if(b<=72){b*=4;for(var e=Qe[b],f=0;f<b;f+=4)e[f]=v[d+4*f>>2],e[f+1]=v[d+(4*f+4)>>2],e[f+2]=v[d+(4*f+8)>>
2],e[f+3]=v[d+(4*f+12)>>2]}else e=v.subarray(d>>2,d+b*16>>2);R.uniformMatrix2fv(Z(R.Eg,a),!!c,e)}},Uc:(a,b,c,d)=>{b&&R.uniformMatrix2x3fv(Z(R.Eg,a),!!c,v,d>>2,b*6)},Sc:(a,b,c,d)=>{b&&R.uniformMatrix2x4fv(Z(R.Eg,a),!!c,v,d>>2,b*8)},Ed:(a,b,c,d)=>{if(S.version>=2)b&&R.uniformMatrix3fv(Z(R.Eg,a),!!c,v,d>>2,b*9);else{if(b<=32){b*=9;for(var e=Qe[b],f=0;f<b;f+=9)e[f]=v[d+4*f>>2],e[f+1]=v[d+(4*f+4)>>2],e[f+2]=v[d+(4*f+8)>>2],e[f+3]=v[d+(4*f+12)>>2],e[f+4]=v[d+(4*f+16)>>2],e[f+5]=v[d+(4*f+20)>>2],e[f+6]=
v[d+(4*f+24)>>2],e[f+7]=v[d+(4*f+28)>>2],e[f+8]=v[d+(4*f+32)>>2]}else e=v.subarray(d>>2,d+b*36>>2);R.uniformMatrix3fv(Z(R.Eg,a),!!c,e)}},Tc:(a,b,c,d)=>{b&&R.uniformMatrix3x2fv(Z(R.Eg,a),!!c,v,d>>2,b*6)},Qc:(a,b,c,d)=>{b&&R.uniformMatrix3x4fv(Z(R.Eg,a),!!c,v,d>>2,b*12)},Dd:(a,b,c,d)=>{if(S.version>=2)b&&R.uniformMatrix4fv(Z(R.Eg,a),!!c,v,d>>2,b*16);else{if(b<=18){var e=Qe[16*b],f=v;d>>=2;b*=16;for(var h=0;h<b;h+=16){var k=d+h;e[h]=f[k];e[h+1]=f[k+1];e[h+2]=f[k+2];e[h+3]=f[k+3];e[h+4]=f[k+4];e[h+5]=
f[k+5];e[h+6]=f[k+6];e[h+7]=f[k+7];e[h+8]=f[k+8];e[h+9]=f[k+9];e[h+10]=f[k+10];e[h+11]=f[k+11];e[h+12]=f[k+12];e[h+13]=f[k+13];e[h+14]=f[k+14];e[h+15]=f[k+15]}}else e=v.subarray(d>>2,d+b*64>>2);R.uniformMatrix4fv(Z(R.Eg,a),!!c,e)}},Rc:(a,b,c,d)=>{b&&R.uniformMatrix4x2fv(Z(R.Eg,a),!!c,v,d>>2,b*8)},Pc:(a,b,c,d)=>{b&&R.uniformMatrix4x3fv(Z(R.Eg,a),!!c,v,d>>2,b*12)},Xc:a=>{if(!me(a))return X||=1280,l("GL_INVALID_ENUM in glUnmapBuffer"),0;var b=qd[le(a)];if(!b||!b.th)return X||=1282,l("buffer was never mapped in glUnmapBuffer"),
0;b.access&16||nd(a,b.offset,b.length,b.th);Lf(b.th);b.th=0;return 1},Cd:Te,Bd:a=>{R.validateProgram(U[a])},Ad:(a,b)=>R.vertexAttrib1f(a,b),zd:(a,b)=>{R.vertexAttrib1f(a,v[b>>2])},yd:(a,b,c)=>R.vertexAttrib2f(a,b,c),xd:(a,b)=>{R.vertexAttrib2f(a,v[b>>2],v[b+4>>2])},wd:(a,b,c,d)=>R.vertexAttrib3f(a,b,c,d),vd:(a,b)=>{R.vertexAttrib3f(a,v[b>>2],v[b+4>>2],v[b+8>>2])},ud:(a,b,c,d,e)=>R.vertexAttrib4f(a,b,c,d,e),td:(a,b)=>{R.vertexAttrib4f(a,v[b>>2],v[b+4>>2],v[b+8>>2],v[b+12>>2])},Cb:Ue,$f:Ue,mb:Ue,nd:Ue,
nb:Ue,vc:(a,b,c,d,e)=>R.vertexAttribI4i(a,b,c,d,e),tc:(a,b)=>{R.vertexAttribI4i(a,t[b>>2],t[b+4>>2],t[b+8>>2],t[b+12>>2])},uc:(a,b,c,d,e)=>R.vertexAttribI4ui(a,b,c,d,e),sc:(a,b)=>{R.vertexAttribI4ui(a,u[b>>2],u[b+4>>2],u[b+8>>2],u[b+12>>2])},yc:(a,b,c,d,e)=>{var f=S.fh[a];R.sh?(f.rh=!1,R.vertexAttribIPointer(a,b,c,d,e)):(f.size=b,f.type=c,f.pi=!1,f.stride=d,f.Vh=e,f.rh=!0,f.Ai=function(h,k,m,n,q,w){this.vertexAttribIPointer(h,k,m,q,w)})},sd:Ve,rd:We,Rb:(a,b,c)=>{c=Number(c);R.waitSync(yd[a],b,c)},
r:()=>0,Ha:(a,b,c)=>Xe(a,{ui:t[c>>2],Yh:t[c+4>>2],cj:t[c+8>>2],Yi:b,Kh:t[c+12>>2],Fi:t[c+16>>2]}),$:(a,b)=>{a=O(a);return a?a.requestPointerLock?Ic()?$c(a):b?(Gc($c,2,[a]),1):-2:-1:-4},Wa:a=>{var b=r.length;a>>>=0;if(a>2147483648)return!1;for(var c=1;c<=4;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,Math.ceil(Math.max(a,d)/65536)*65536)-qa.buffer.byteLength+65535)/65536|0;try{qa.grow(d);pa();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},ga:Ye,O:(a,b,c)=>
typeof onbeforeunload=="undefined"?-1:c!==1?-5:Ze(a,b),Y:(a,b,c,d)=>$e(a,b,c,d,12,"blur"),i:Rc,Pa:(a,b,c)=>af(a,b,c),n:(a,b,c)=>{a=O(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},Z:(a,b,c,d)=>$e(a,b,c,d,13,"focus"),W:(a,b,c,d)=>{if(!K.fullscreenEnabled())return-1;a=O(a);if(!a)return-4;bf(a,b,c,d,"webkitfullscreenchange");return bf(a,b,c,d,"fullscreenchange")},ea:(a,b,c)=>Ye()?-1:cf(a,b,c,26,"gamepadconnected"),da:(a,b,c)=>Ye()?-1:cf(a,b,c,27,"gamepaddisconnected"),S:(a,b,
c,d)=>df(a,b,c,d,2,"keydown"),Q:(a,b,c,d)=>df(a,b,c,d,1,"keypress"),R:(a,b,c,d)=>df(a,b,c,d,3,"keyup"),Va:(a,b,c,d)=>{Cc(()=>Q(a)(b),c,d,b)},ca:pc,T:(a,b,c)=>window.screen&&screen.orientation?ef(a,b,c):-1,X:(a,b,c,d)=>document.body?.requestPointerLock?(a=O(a))?ff(a,b,c,d):-4:-1,V:(a,b,c,d)=>gf(a,b,c,d),P:(a,b,c)=>Lc[1]?hf(a,b,c):-4,U:(a,b,c,d)=>(a=O(a))?typeof a.onwheel!="undefined"?jf(a,b,c,d):-1:-4,Ja:a=>document.title=a?A(r,a):"",q:()=>{y("Please compile your program with async support in order to use asynchronous operations like emscripten_sleep")},
Na:(a,b)=>{var c=b>>2;b={alpha:!!p[b+0],depth:!!p[b+1],stencil:!!p[b+2],antialias:!!p[b+3],premultipliedAlpha:!!p[b+4],preserveDrawingBuffer:!!p[b+5],powerPreference:kf[t[c+2]],failIfMajorPerformanceCaveat:!!p[b+12],desynchronized:!!p[b+33],Li:t[c+4],Pj:t[c+5],Hi:p[b+24],$i:p[b+25],Tj:t[c+7],Wj:p[b+32]};a=O(a);return!a||b.$i?0:Kd(a,b)},aa:a=>{S==a&&(S=0);S===vd[a]&&(S=null);typeof K=="object"&&K.qj(vd[a].jh.canvas);vd[a]?.jh.canvas&&(vd[a].jh.canvas.zh=void 0);vd[a]=null},ba:a=>{S=vd[a];g.ctx=R=S?.jh;
return!a||R?0:-5},gb:(a,b)=>{var c=0,d=0,e;for(e of nf()){var f=b+c;u[a+d>>2]=f;c+=B(e,r,f,Infinity)+1;d+=4}return 0},hb:(a,b)=>{var c=nf();u[a>>2]=c.length;a=0;for(var d of c)a+=Pa(d)+1;u[b>>2]=a;return 0},ka:function(a){try{var b=Cb(a);Pb(b);return 0}catch(c){if(typeof J=="undefined"||c.name!=="ErrnoError")throw c;return c.Ng}},ab:function(a,b,c,d){try{a:{var e=Cb(a);a=b;for(var f,h=b=0;h<c;h++){var k=u[a>>2],m=u[a+4>>2];a+=8;try{var n=e,q=k,w=m,z=f,G=p;if(w<0||z<0)throw new C(28);if(n.fd===null)throw new C(8);
if((n.flags&2097155)===1)throw new C(8);if(E(n.node.mode))throw new C(31);if(!n.Gg.read)throw new C(28);var F=typeof z!="undefined";if(!F)z=n.position;else if(!n.seekable)throw new C(70);var L=n.Gg.read(n,G,q,w,z);F||(n.position+=L);var H=L}catch(T){if(b>0&&T instanceof C&&(T.Ng==6||T.Ng==6))break;throw T;}if(H<0){var N=-1;break a}b+=H;if(H<m)break;typeof f!="undefined"&&(f+=H)}N=b}u[d>>2]=N;return 0}catch(T){if(typeof J=="undefined"||T.name!=="ErrnoError")throw T;return T.Ng}},Xa:function(a,b,c,
d){b=b<-9007199254740992||b>9007199254740992?NaN:Number(b);try{if(isNaN(b))return 22;var e=Cb(a);Qb(e,b,c);ta[d>>3]=BigInt(e.position);e.ji&&!b&&c===0&&(e.ji=null);return 0}catch(f){if(typeof J=="undefined"||f.name!=="ErrnoError")throw f;return f.Ng}},ia:function(a,b,c,d){try{var e=Cb(a);a=b;if(c==1)var f=Rb(e,p,u[a>>2],u[a+4>>2]);else{for(var h=b=0,k=a;h<c;h++,k+=8)b+=u[k+4>>2];var m=new Uint8Array(b);for(h=k=0;h<c;h++,a+=8){var n=u[a>>2],q=u[a+4>>2];m.set(r.subarray(n,n+q),k);k+=q}f=Rb(e,m,0,b)}u[d>>
2]=f;return 0}catch(w){if(typeof J=="undefined"||w.name!=="ErrnoError")throw w;return w.Ng}},la:Ld,j:Md,m:Nd,h:Od,c:Pd,B:Qd,N:Rd,z:Sd,ie:Td,cg:Ud,J:Vd,E:Wd,L:Xd,na:Yd,pa:Zd,d:$d,l:ae,oa:be,x:ce,y:de,C:je,f:ke,t:ne,M:oe,u:pe,ma:qe,H:ye,I:ze,v:De,D:He,w:Je,G:Ke,K:Ne,F:Oe,b:Pe,A:Se,k:Te,e:Ve,s:We};function Of(a=[]){var b=Mf;a.unshift(ea);var c=a.length,d=Mc((c+1)*4),e=d,f;for(f of a)u[e>>2]=Nc(f),e+=4;u[e>>2]=0;try{var h=b(c,d);oa=h;qc(h)}catch(k){rc(k)}}
async function Pf(){var a=da;ua();eb&&await db();var b=g.setStatus;b&&(b("Running..."),await new Promise(c=>setTimeout(c,1)),setTimeout(b,1,""));na||(g.noFSInit||rb||Sb(),Qf.eg(),sb=!1,g.onRuntimeInitialized?.(),g.noInitialRun||Of(a),wa())}var Qf;
(async function(){function a(d){d=Qf=d.exports;Lf=d.gg;Y=d.hg;Mf=g._main=d.ig;Af=g._SDL_free=d.jg;g._SDL_calloc=d.kg;xf=g._SDL_malloc=d.lg;g._SDL_realloc=d.mg;Gf=g._Emscripten_force_free=d.ng;g._SDLEmscriptenCameraPermissionOutcome=d.og;g._SDLEmscriptenThreadIterate=d.pg;Bf=g._Emscripten_HandlePointerEnter=d.qg;Cf=g._Emscripten_HandlePointerLeave=d.rg;Df=g._Emscripten_HandlePointerGeneric=d.sg;zf=g._Emscripten_HandleMouseButtonUpGlobal=d.tg;Ef=g._Emscripten_SendDragEvent=d.ug;If=g._Emscripten_SendDragCompleteEvent=
d.vg;Ff=g._Emscripten_SendDragTextEvent=d.wg;Hf=g._Emscripten_SendDragFileEvent=d.xg;yf=g._Emscripten_HandleLockKeysCheck=d.yg;Kf=g._Emscripten_SendSystemThemeChangedEvent=d.zg;Jf=g._requestFullscreenThroughSDL=d.Ag;Pc=d.Bg;Mc=d.Cg;Oc=d.Dg;qa=d.dg;Vc=d.fg;pa();return Qf}var b={a:Nf},c=g.instantiateWasm;if(c)return new Promise(d=>{c(b,e=>d(a(e)))});ya??=g.locateFile?g.locateFile("beatup_run.wasm",ia):ia+"beatup_run.wasm";return function(d){return a(d.instance)}(await Ba(b))})().then(()=>Pf());
